---
permalink: windows/concept-what-snapmanager-for-oraclesnapmanager-for-sap-does.html 
sidebar: sidebar 
keywords: snapmanager, sap, simplify, simplifies, automate, database, backup, recovery, clone, leverage, snapshot, copies, copy, snaprestore, flexclone, technology, technologies 
summary: 適用於SAP的解決方案可利用Snapshot複本、功能複本和FlexClone技術、簡化資料庫備份、還原及複製作業、並使其自動化。SnapManager SnapRestore 
---
= SAP的功能SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於SAP的解決方案可利用Snapshot複本、功能複本和FlexClone技術、簡化資料庫備份、還原及複製作業、並使其自動化。SnapManager SnapRestore

支援下列效益給資料庫管理員（DBA）SnapManager ：

* 使用資料庫設定檔
+
** 您可以在設定檔中組織及保留主機與資料庫資訊。
+
當您根據設定檔啟動備份時、您可以重複使用資訊、而不必在每個備份中重新輸入資訊。此外、您也可以使用設定檔快速監控作業。SnapManager

** 在設定檔中、您可以定義Snapshot複本命名模式並輸入自訂（字首或字尾）文字、以便所有Snapshot複本都能使用符合業務原則的相同命名慣例。
** 您不需要知道儲存系統名稱、因為資料庫檔案會自動對應至相關的儲存設備。
** 建立新的設定檔時、您可以指定選項、將歸檔記錄備份與資料檔案備份分開。
+
您也可以更新現有的設定檔、將歸檔記錄備份與資料檔案備份分開。



* 執行資料庫備份作業
+
** 完整及部分資料庫的備份
+
*** 您可以以節省空間的方式快速建立完整或部分備份、以便更頻繁地執行備份。
+
完整資料庫備份包含單一備份中的所有資料檔案、控制檔及記錄檔。

+
部分資料庫備份包含指定的資料檔案或表格空間、所有控制檔及所有歸檔記錄檔。

*** 您可以使用後處理指令碼來保護備份至二線儲存設備。
*** 您可以排程每小時、每週、每日、每月或無限的備份。


** 分開備份資料檔案和歸檔記錄檔
+
*** 使用支援（3.2或更新版本）、您可以分別備份資料檔案和歸檔記錄檔。SnapManager若要執行此作業、您必須指定選項、以便在建立或更新設定檔時分隔歸檔記錄檔。
*** 您可以在保留原則中指定保留資料檔案備份的計數和持續時間。
*** 您可以指定歸檔記錄檔備份在歸檔記錄保留期間內保留的持續時間。
*** 透過使用重複的歸檔記錄檔來釋放歸檔記錄備份、並使用獨特的歸檔記錄檔來保留歸檔記錄備份、即可將歸檔記錄備份整合至最少的備份數量。SnapManager不過、您也可以選擇停用此整合。




* 管理歸檔記錄檔
+
** 利用支援（3.2或更新版本）、您可以從歸檔記錄目的地剪除歸檔記錄檔。SnapManager
+
清除包含這些歸檔記錄檔檔案的歸檔記錄備份時、會釋出剪除的歸檔記錄檔所佔用的空間。

** 在將歸檔記錄檔從歸檔記錄目的地剪除之前、可確保備份歸檔記錄檔。SnapManager
+
未備份的歸檔記錄檔不會被剪除。

** 使用此功能可確保歸檔記錄檔會在剪除Data Guard主資料庫的歸檔記錄檔時、傳送至Data Guard待命資料庫。SnapManager
** 支援的支援功能可確保Oracle的Stream擷取程序（若有）擷取歸檔記錄檔。SnapManager
** 建議
+
*** 若要有效管理歸檔記錄目的地空間、您必須建立歸檔記錄備份、並剪除歸檔記錄檔。


** 透過使用重複的歸檔記錄檔來釋出歸檔記錄備份、並使用獨特的歸檔記錄檔來保留歸檔記錄備份、將歸檔記錄備份整合至包含最少備份數的狀態。SnapManager
+
不過、您也可以選擇停用此整合。歸檔記錄備份會釋出、其中包含重複的歸檔記錄檔、並保留具有唯一歸檔記錄的單一備份。



* 執行資料庫還原作業
+
** 您可以執行檔案型還原作業。
+
您也可以在執行作業之前、預覽還原作業、並取得還原作業的檔案分析。

** 您可以使用SnapRestore 還原功能、縮短還原資料庫的平均時間。
** 使用者可透過使用備份中的歸檔記錄檔、自動恢復資料庫（3.2或更新版本）、即使歸檔記錄檔不在歸檔記錄目的地中也沒問題。SnapManager
+
使用外部位置的歸檔記錄檔、即可在特定範圍內使用內部位置的還原資料庫（3.2或更新版本）SnapManager 。



* 執行資料庫複製以進行測試與開發
+
** 您可以建立資料庫的複本、以便在正式作業環境之外設定資料庫。
+
例如、您可以在開發與測試環境中複製、以測試升級至重要系統的作業。

** 您可以複製一線儲存系統上的資料庫。
** 使用支援的更新版本（3.2或更新版本）、您可以使用備份中的歸檔記錄檔來複製資料檔案備份。SnapManager
+
*** 您只能在備份歸檔記錄時複製資料檔案備份。
*** 如果歸檔記錄檔可在特定範圍內個別進行的歸檔記錄備份中使用、您也可以複製資料檔案備份。
*** 您也可以從Oracle可存取的任何外部位置、使用歸檔記錄檔、在特定程度上複製獨立資料庫的資料檔案備份。
*** 如果備份可從外部位置取得、您可以在複製期間指定外部位置、以便將複製的資料庫還原至一致狀態。


** 不支援僅複製歸檔記錄備份。


* 一般
+
** 與SAP的BR*工具整合。
+
BR*工具套件提供SAP工具、例如：BRRCHIVE、BRBACKUP、BRCONNECT、BRRECOVERR、BRRESTORE、 BRSPACE和BRTOOLS。





支援下列效益給儲存管理員：SnapManager

* 支援不同的SAN傳輸協定。
* 可讓您根據最適合您環境的備份類型（完整或部分）來最佳化備份。
* 建立節省空間的資料庫備份。
* 建立節省空間的複本。


支援下列Oracle功能：SnapManager

* 可利用Oracle的RMAN將備份資料編錄為目錄。SnapManager
+
如果使用RMAN、DBA可以使用SnapManager 還原功能、並保留所有RMAN功能的價值、例如區塊層級還原。執行恢復或還原時、可讓RMAN使用Snapshot複本。SnapManager例如、您可以使用RMAN還原資料表空間內的資料表、並從SnapManager 由Oracle所製作的Snapshot複本執行完整的資料庫和資料表空間還原和還原。RMAN恢復目錄不應位於要備份的資料庫中。


