---
permalink: windows/concept-what-database-backup-scheduling-is.html 
sidebar: sidebar 
keywords: schedule, update, monitor, backup, database, graphical, user, interface 
summary: 您可以使用圖形化使用者介面的排程索引標籤來排程、更新及監控資料庫的備份。 
---
= 什麼是資料庫備份排程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用圖形化使用者介面的排程索引標籤來排程、更新及監控資料庫的備份。

下表說明一些常見的排程問題：

|===
| 問題 | 答 


 a| 
當伺服SnapManager 器重新啟動時、排程的備份會發生什麼變化？
 a| 
當伺服SnapManager 器重新啟動時、它會自動重新啟動所有排程。但是SnapManager 、對於任何遺漏的事件、不需執行此動作。



 a| 
當兩個資料庫同時排程進行兩個備份時、會發生什麼情況？
 a| 
執行一個備份作業時、即可同時啟動一個備份作業、然後讓備份作業平行執行。SnapManager例如、如果資料庫管理員為六個不同的資料庫設定檔建立六個每日備份排程、以便在上午1：00執行、則所有六個備份都會平行執行。

如果排定在短時間內在單一資料庫設定檔上執行多個備份、SnapManager 則該伺服器只會執行保留時間最長的備份作業。

在開始備份作業之前SnapManager 、由下列項目由支援部門決定：

* 在過去30分鐘內、是否有另一個排程成功建立同一個設定檔的備份（保留率較高）？
* 在接下來的30分鐘內、是否會有另一個排程嘗試為同一個設定檔建立更具保留力的備份？


如果任一問題的答案為「是」、SnapManager 則不執行此備份。

例如、資料庫管理員可能會為資料庫設定檔建立每日、每週及每月排程、所有這些都排定在上午1：00進行備份當三個備份排定在同一天的上午1：00同時進行時、SnapManager 就只會根據每月排程執行備份作業。

30分鐘的時間範圍可在SnapManager 一個更新檔中變更。



 a| 
備份作業是在哪個使用者下執行？
 a| 
此作業會在建立排程的使用者下執行。不過、如果您同時擁有資料庫設定檔和主機的有效認證資料、您可以將此變更為自己的使用者ID。例如、透過針對Aveda Davis建立的備份排程啟動排程備份內容、Stella Morrow可以選取她的使用者ID來執行此作業、做為執行排程備份的使用者。



 a| 
無法與原生作業系統排程器互動的原因為何？SnapManager
 a| 
在支援服務器上、您無法透過作業系統的原生排程器檢視排程備份。SnapManager例如、建立排程備份之後、您不會在「排程工作」視窗中看到新的項目。



 a| 
如果圖形使用者介面和伺服器的時鐘不同步、會發生什麼情況？
 a| 
用戶端和伺服器上的時鐘不會同步。因此、您可以排程在用戶端上、但在伺服器上、開始時間是未來的備份時間。

對於重複備份、伺服器仍會執行要求。例如、如果伺服器收到從08年1月30日下午3點開始執行每小時備份的要求但目前時間是下午3：30當天、伺服器會在下午4：00執行第一次備份並持續每小時執行備份。

不過、對於一次性備份、伺服器會處理下列要求：

* 如果開始時間是目前伺服器時間的最後五分鐘內、SnapManager 則會立即開始備份。
* 如果開始時間超過五分鐘、SnapManager 則不會啟動備份。


例如、請考慮下列案例：

* 圖形介面主機中的時鐘比實際時間落後三分鐘。
* 客戶目前的時間為上午8：58
* 您排定在上午9：00進行一次性備份
* 您排定另一個一次性備份於上午8：30進行


當伺服器收到第一個要求時、伺服器上的時間為上午9：01儘管備份的開始時間已經過去、SnapManager 但仍會立即執行備份。

當伺服器收到第二個要求時、備份的開始時間過去超過五分鐘。您會收到一則訊息、指出排程要求因為開始時間已過去而失敗。

您可以在SnapManager 一個更新檔案中變更五分鐘的時間。



 a| 
刪除設定檔時、設定檔的排程備份會發生什麼事？
 a| 
刪除資料庫設定檔時SnapManager 、伺服器會刪除為該設定檔定義的排程備份。



 a| 
排程備份在使用自然時間或變更SnapManager 伺服器時間時、如何運作？
 a| 
由於採用自然節約時間或變更了伺服器時間、所以支援的排程也會受到影響。SnapManager SnapManager

變更伺服SnapManager 器時間時、請考量下列影響：

* 在觸發備份排程之後、SnapManager 如果還原伺服器時間、則不會再次觸發備份排程。
* 如果在排定的開始時間之前開始使用「夏時制」、則會自動觸發備份排程。
* 例如、如果您在美國、而且排定在上午4點進行每小時備份這應該每4小時進行一次、備份將在三月和十一月調整夏令時之前和之後的第二天、於上午4點、上午8點、上午12點、上午4點、下午8點和午夜進行。
* 如果備份排定在上午2：30進行、請注意下列事項每晚：
+
** 當時鐘恢復一小時時、由於備份已經觸發、備份不會再次觸發。
** 當時鐘向前快轉一小時時、便會立即觸發備份。如果您在美國境內、想要避免此問題、您必須排定備份時間、從上午2：00開始至上午3：00時間間隔。




|===