---
permalink: windows/concept-what-snapmanager-operation-states-are.html 
sidebar: sidebar 
keywords: snapmanager, operation, backup, restore, clone, state, indicate, progress 
summary: 支援各種作業（備份、還原和複製）的狀態可能不同、每種狀態都會顯示作業進度。SnapManager 
---
= 運作狀態為何SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援各種作業（備份、還原和複製）的狀態可能不同、每種狀態都會顯示作業進度。SnapManager

|===
| 作業狀態 | 說明 


 a| 
成功
 a| 
作業已成功完成。



 a| 
執行中
 a| 
作業已開始、但尚未完成。例如、備份需要兩分鐘的時間、排定在上午11：00進行。當您在上午11：01檢視*排程*索引標籤時、該作業會顯示為執行中。



 a| 
找不到作業
 a| 
排程尚未執行、或上次執行的備份已刪除。



 a| 
失敗
 a| 
作業失敗。自動執行中止程序並清除作業。SnapManager

|===


== 可恢復和不可恢復的事件

可恢復SnapManager 的故障：

* 資料庫不會儲存在執行Data ONTAP 還原的儲存系統上。
* 不安裝Windows適用的系統、或無法存取儲存系統。SnapDrive
* 如果磁碟區空間不足、已達到Snapshot複本的最大數量、或發生非預期的例外狀況、則無法建立Snapshot複本或配置儲存設備。SnapManager


發生可恢復的事件時SnapManager 、現象會執行中止程序、並嘗試將主機、資料庫和儲存系統恢復至啟動狀態。如果中止程序失敗、SnapManager 則將事件視為不可恢復的事件。

發生下列任一情況時、都會發生不可恢復（頻外）事件：

* 發生系統問題、例如主機故障時。
* 停止執行此程序。SnapManager
* 當儲存系統故障、邏輯單元號碼（LUN）或儲存磁碟區離線、或網路故障時、頻內中止作業會失敗。


發生不可恢復的事件時SnapManager 、現象之一是立即執行中止程序。主機、資料庫和儲存系統可能尚未返回初始狀態。如果是這種情況、SnapManager 您必須在執行完此動作後、刪除孤立的Snapshot複本並移除SnapManager 此等不鎖定檔案、以執行清除作業。

如果您要刪除SnapManager 此等不鎖定檔案、請瀏覽至目標機器上的「$oracle_home'」、然後刪除「shm_Lock_TarkDBName」檔案。刪除檔案後、您必須重新啟動SnapManager SAP伺服器的功能。
