---
permalink: windows/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, information, smsap 
summary: 您可以執行備份還原命令來還原資料庫或部分資料庫的備份、然後選擇性地還原資料庫資訊。 
---
= smsap備份還原命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行「備份還原」命令來還原資料庫或部分資料庫的備份、然後選擇性地還原資料庫資訊。



== 語法

[listing]
----

smsap backup restore
-profile profile_name
[-label label | -id id]
[-files files [files...] |
-tablespaces tablespaces [tablespaces...]] |
-complete | -controlfiles]
[-recover {-alllogs | -nologs | -until until} [-using-backup-controlfile]]
[-restorespec restorespec | ]]
[-preview]

[-recover-from-location path1 [, path2]]
[-taskspec taskspec]
[-dump]
[-force]
[-quiet | -verbose]
----


== 參數

* *。設定檔_profile_name_`*
+
指定您要還原的資料庫。設定檔包含資料庫和其他資料庫資訊的識別碼。

* *標籤_name_`*
+
使用指定的標籤還原備份。

* *（id_guid_`*）
+
使用指定的Guid還原備份。當SnapManager 您建立備份時、會產生由支援所產生的GUID。您可以使用「msap備份清單」命令來顯示每個備份的Guid。

* *「選擇全部或指定的檔案」*
+
您也可以選擇使用下列其中一個選項：

+
** 「-Complete」：還原備份中的所有資料檔案。
** -`-tablespaceslist'：僅從備份中恢復指定的表空間。
+
您必須使用空格來分隔清單中的名稱。

** 文件列表：僅從備份中恢復指定的數據文件。
+
您必須使用空格來分隔清單中的名稱。如果資料庫正在執行、SnapManager 則由支援驗證可確保包含檔案的資料表空間離線。



* *控制檔*
+
還原控制檔。利用此功能、您可以在單一作業中還原控制檔及備份中的資料檔案。SnapManagercontrolfilers'選項與其他還原範圍參數（如「-complete」、「-tabl空間」及「-filers」）無關。

* *（復原）*
+
還原資料庫後將其恢復。您也必須SnapManager 使用下列其中一個選項、指定要讓效益管理系統恢復資料庫的點：

+
** noslogs：將資料庫恢復到備份時間、不套用任何記錄。
+
您可以使用此參數進行線上或離線備份。

** 「-alllogs」：將資料庫恢復到最後一筆交易或提交、並套用所有必要的記錄。
** 「直到日期」：將資料庫恢復至指定的日期和時間。
+
您必須使用年月日期：小時：分：秒（_year-mm-dd:hh：mm:ss_）格式。視資料庫設定而定、若為小時、請使用12小時或24小時格式。

** 「直到SCN」：將資料檔案轉送到指定的系統變更編號（SCN）為止。
** 使用備份控制檔：使用備份控制檔恢復資料庫。


* *還原程式*
+
可讓您將資料還原至作用中檔案系統、並透過每個原始Snapshot複本對應至作用中檔案系統、從指定的資料還原資料。如果您未指定選項、SnapManager 則由主儲存設備上的Snapshot複本還原資料。您可以指定下列其中一個選項：

+
** restoresespec：指定要還原的資料和還原格式。


* *（預覽）*
+
顯示下列資訊：

+
** 將使用哪種還原機制（儲存端檔案系統還原、儲存端檔案還原或主機端檔案複本還原）來還原每個檔案
** 當您指定「-verbose」選項時、為什麼不使用更有效率的機制來還原每個檔案。如果您使用「-preview」（預覽）選項、您必須瞭解下列事項：
** 「-force」選項對命令沒有影響。
** 「-recover'」選項對命令沒有影響。若要預覽還原作業、必須掛載資料庫。如果您想預覽還原計畫、但目前尚未掛載資料庫、SnapManager 則會掛載資料庫。如果無法掛載資料庫、則命令將會失敗、SnapManager 而將資料庫恢復為原始狀態。


+
「preview」（預覽）選項最多可顯示20個檔案。您可以設定要顯示在「smsap.config檔案」中的檔案數目上限。

* *（從位置恢復）*
+
指定歸檔記錄檔的外部歸檔記錄位置。從外部位置取得歸檔記錄檔、並將其用於恢復程序。SnapManager

* *（taskspec*）
+
指定工作規格XML檔案、以供還原作業的預先處理活動或後處理活動使用。您必須提供工作規格XML檔案的完整路徑。

* *（轉儲）*
+
指定在還原作業之後收集傾印檔。

* *（力）*
+
如有必要、可將資料庫狀態變更為低於目前狀態。

+
根據預設、SnapManager 在作業期間、無法將資料庫狀態變更為較高的狀態。不需要此選項SnapManager 、即可將資料庫變更為較高的狀態。

* *（靜音）*
+
僅在主控台顯示錯誤訊息。預設設定為顯示錯誤和警告訊息。

* *（冗長）*
+
在主控台顯示錯誤、警告和資訊訊息。您可以使用此選項來瞭解為何無法使用更有效率的還原程序來還原檔案。





== 範例

下列範例會還原資料庫及控制檔：

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----