---
permalink: windows/reference-error-messages.html 
sidebar: sidebar 
keywords: information, error, message, associate, snapmanager, operation 
summary: 您可以找到與不同SnapManager 的故障操作相關的錯誤訊息資訊。 
---
= 錯誤訊息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以找到與不同SnapManager 的故障操作相關的錯誤訊息資訊。



== 最常見的錯誤訊息

下表列出SnapManager 一些與SAP適用的一些最常見且最重要的錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「D-10038：檔案系統不可寫入」。
 a| 
不具備檔案系統的寫入權限。SnapManager
 a| 
您必須確保SnapManager 這個過程對檔案系統具有寫入權限。修正此問題之後、您可能需要執行另一個快照。



 a| 
「MSAP-5075：無法建立設定檔。您必須正確設定DP/XDP關係、或根據基礎關係選擇正確的保護原則。
 a| 
基礎磁碟區並不屬於SnapVault SnapMirror或SnapMirror關係。
 a| 
您必須在來源與目的地磁碟區之間設定資料保護關係、然後初始化關係。



 a| 
您已為設定檔指定相同的名稱[SMSAP-05503]。指定不同的名稱以重新命名設定檔。
 a| 
儲存庫中無法存在名稱相同的設定檔。
 a| 
提供未使用的設定檔名稱。



 a| 
「MSAP-05505：無法更新資料集中繼資料」。
 a| 
資料集可能已刪除或不存在。
 a| 
在更新資料集中繼資料之前、請使用NetApp管理主控台驗證資料集是否存在。



 a| 
「MSAP-05506：您無法更新設定檔、因為設定檔上正在執行作業。您必須等到作業完成後再更新設定檔
 a| 
在進行備份、還原和複製作業時、無法更新設定檔。
 a| 
完成目前作業後、請更新設定檔。



 a| 
「MSAP-05509：archivelog主要保留期間無效-請指定正整數值」。
 a| 
歸檔記錄備份的保留時間不能為負值。
 a| 
指定歸檔記錄備份保留期間的正值。



 a| 
「MSAP-07463：此備份還原需要資料庫處於必要狀態。無法將資料庫移至所需狀態。
 a| 
資料庫未處於備份作業所需的狀態。
 a| 
在建立備份複本之前、請先檢查資料庫是否處於相關狀態。要還原的資料庫狀態取決於您要執行的還原程序類型、以及要包含的檔案類型。



 a| 
「MSAP-09315：執行儲存庫升級或更新作業之後、除非您以通知主機詳細資料更新摘要通知、否則您可能不會收到先前版本中所設定通知的摘要通知。」
 a| 
在循環升級後、系統儲存庫未設定通知設定。
 a| 
在循環升級之後、請更新摘要通知設定以接收通知。



 a| 
「MSAP-02076：標籤名稱不得包含任何特殊字元、但不得包含底線。」
 a| 
標籤名稱包含非底線的特殊字元。
 a| 
標籤名稱在設定檔中必須是唯一的。名稱可以包含字母、數字、底線（_）和連字號（-）（但不能以連字號開頭）。請確定標籤中除了底線之外、沒有任何特殊字元。



 a| 
「MSAP-06308：嘗試開始排程時發生例外狀況：Java.LANG.NullPointerException」
 a| 
設定檔主機的完整網域名稱（FQDN）已設定、而非系統的主機名稱、而且無法解析設定檔主機的FQDN。
 a| 
請確定您使用的是系統的主機名稱、而非FQDN。



 a| 
「執行失敗恢復步驟：Oracle-10003：針對Oracle資料庫執行SQL「刪除磁碟群組；控制磁碟群組名稱；包括內容」時發生錯誤+ASM1：ora-15039：磁碟群組未中斷ORA-15027：磁碟群組的作用中使用；「控制磁碟群組名稱」排除其卸載。
 a| 
使用控制檔還原備份的作業無法刪除控制磁碟群組。如果控制磁碟群組中有過時的備份控制檔、就會發生此問題。
 a| 
識別過時的備份控制檔、然後手動刪除。



 a| 
「RMAN-06004：恢復目錄資料庫中的Oracle錯誤：ora-01424：轉義字元之後缺少或不合法的字元」
 a| 
當將NetApp與RMAN整合時、備份建立作業無法從目錄中移除備份複本SnapManager 。
 a| 
檢查是否有任何外部指令碼用於從RMAN移除備份。在RMAN中執行「交叉檢查備份」命令以更新RMAN儲存庫、並執行「REsync型錄」命令、將目標資料庫的控制檔與恢復型錄同步。



 a| 
[debug]：剪除備份時發生異常。Java.LANG.IllegalStateException：[Assertion failed]-此狀態不變項必須為true（真）
 a| 
為單一作業ID建立多個Snapshot複本。
 a| 
手動刪除Snapshot複本、並使用指令碼刪除儲存庫中的項目。



 a| 
記錄檔中的系統時間和SnapManager 顯示時間不相符或不同步。
 a| 
Java 7尚不支援時區變更。
 a| 
套用Oracle提供的「tzupdater」修補程式。



 a| 
「DISC-00001：無法探索儲存設備：下列識別碼不存在或不是預期的類型：ASM檔案」
 a| 
資料或控制檔或重作記錄會在ASM資料庫中多重複使用。
 a| 
移除Oracle多工處理。



 a| 
「0001-SMSAP-02016：資料庫中可能有外部資料表未備份做為此備份作業的一部分（因為在此備份期間未開啟資料庫、所以無法查詢all_external位置以判斷外部資料表是否存在）」。
 a| 
不備份外部表格（例如、未儲存在.dbf檔案中的表格）SnapManager 。發生此問題的原因是資料庫在備份期間未開啟、SnapManager 無法判斷是否正在使用任何外部表格。
 a| 
資料庫中可能有外部資料表未在此作業中備份（因為資料庫在備份期間未開啟）。



 a| 
「0002-332管理錯誤：無法檢查SD.snapshot。Clone存取磁碟區「volume _name」、以取得Operations Manager伺服器上的使用者使用者名稱「Dfm_server」。原因：指定的資源無效。無法在Operations Manager伺服器「Dfm_server」上找到其ID
 a| 
未設定適當的存取權限和角色。
 a| 
為嘗試執行命令的使用者設定存取權限或角色。



 a| 
「警告」流程11011：作業中止[ERROR]流程-111008：作業失敗：Java堆空間。
 a| 
資料庫中的歸檔記錄檔數目超過允許的上限。
 a| 
. 瀏覽SnapManager 至安裝目錄。
. 開啟「laune-java」檔案。
. 增加"Java -Xmx160m" Java堆空間參數的值。例如、您可以將預設值160m至200m修改為「java -Xmx200m」。




 a| 
「MSAP-21019：目的地的歸檔記錄剪除失敗：「e:\dest」、原因是：「oracle-00101：執行RMAN命令時發生錯誤：[DELETE NOPROMPT ARCHIVELOG 'E:\Dest']」
 a| 
其中一個目的地的歸檔記錄剪除失敗。在這種情況SnapManager 下、透過其他目的地、將檔案記錄檔剪除。如果從作用中檔案系統手動刪除任何檔案、RMAN將無法從該目的地剪除歸檔記錄檔。
 a| 
從SnapManager 該主機連線至RMAN。執行RMAN「Crosscheck ARCHIVELOG ALL」命令、並在歸檔記錄檔上再次執行剪除作業。



 a| 
「MSAP-13032：無法執行作業：歸檔記錄Prune。根本原因：RMAN例外：Oracle-00101：執行RMAN命令時發生錯誤。
 a| 
歸檔記錄檔會從歸檔記錄目的地手動刪除。
 a| 
從SnapManager 該主機連線至RMAN。執行RMAN「Crosscheck ARCHIVELOG ALL」命令、並在歸檔記錄檔上再次執行剪除作業。



 a| 
「無法剖析Shell輸出：（Java.util.regex.Matcher [Pattern=Command完成。region=018 lastmatch=]）不相符（名稱：backup_script）無法剖析Shell輸出：（Java.util.regex.Matcher [模式=命令完成。region=0.25 lastmatch=]）不相符（說明：備份指令碼）

「無法剖析Shell輸出：（Java.util.regex.Matcher [Pattern=Command完成。region=0.9 lastmatch=]）不符（timeout：0）
 a| 
環境變數未在工作前或工作後指令碼中正確設定。
 a| 
檢查工作前或工作後指令碼是否符合標準SnapManager 的版本資訊插件架構。如需在指令碼中使用環境變數的其他資訊、請參閱 xref:concept-operations-in-task-scripts.adoc[工作指令碼中的作業]。



 a| 
「ORA -01450：超過最大金鑰長度（6398）」。
 a| 
當您從SnapManager 適用於SAP的32位元3.2升級至SnapManager 適用於SAP的32位元3.3時、升級作業會失敗並顯示此錯誤訊息。此問題可能是因為下列原因之一所致：

* 儲存庫所在的資料表空間區塊大小低於8k。
* 將「NLS_lim_語 義」參數設為「char」。

 a| 
您必須將值指派給下列參數：

* "block_size=*8192*
* "NLS_LONG"=*位元組*


修改參數值之後、您必須重新啟動資料庫。

如需詳細資訊、請參閱知識庫文章2017632。

|===


== 與資料庫備份程序相關的錯誤訊息（2000系列）

下表列出與資料庫備份程序相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-02066：您無法刪除或釋放歸檔記錄備份「資料記錄」、因為備份與資料備份「資料記錄」有關。
 a| 
歸檔記錄備份會與資料檔案備份一起進行、您嘗試刪除歸檔記錄備份。
 a| 
使用「_-force_」選項刪除或釋出備份。



 a| 
「MSAP-02067：您無法刪除或釋出歸檔記錄備份「資料記錄」、因為備份與資料備份「資料記錄」相關、而且在指派的保留期間內。」
 a| 
歸檔記錄備份會與資料庫備份相關聯、而且在保留期間內、您嘗試刪除歸檔記錄備份。
 a| 
使用「-force」選項來刪除或釋放備份。



 a| 
「MSAP-07142：由於排除模式<exclude>模式、已排除歸檔的記錄。」
 a| 
您可以在設定檔建立或備份建立作業期間排除某些歸檔記錄檔。
 a| 
無需採取任何行動。



 a| 
「MSAP-07155：<count>歸檔的記錄檔不存在於作用中的檔案系統中。這些歸檔的記錄檔將不會包含在備份中。
 a| 
在設定檔建立或備份建立作業期間、活動檔案系統中不存在歸檔記錄檔。這些歸檔的記錄檔不包含在備份中。
 a| 
無需採取任何行動。



 a| 
「MSAP-07148：歸檔的記錄檔無法使用」。
 a| 
在設定檔建立或備份建立作業期間、不會為目前資料庫建立任何歸檔記錄檔。
 a| 
無需採取任何行動。



 a| 
「SAP-07150：找不到歸檔的記錄檔」。
 a| 
在設定檔建立或備份建立作業期間、檔案系統中遺失或排除所有歸檔記錄檔。
 a| 
無需採取任何行動。



 a| 
「MSAP-13032：無法執行作業：建立備份。根本原因：Oracle-20001：嘗試將資料庫執行個體dfcln1的狀態變更為開啟時發生錯誤：Oracle-20004：預期在沒有RESETLOGS選項的情況下能夠開啟資料庫、但Oracle報告需要使用RESETLOGS選項開啟資料庫。為了避免意外重設記錄、此程序將不會繼續。請確保在沒有RESETLOGS選項的情況下開啟資料庫、然後再試一次。
 a| 
您嘗試備份使用-'no -resettlogs（無重新設定記錄）選項所建立的複製資料庫。複製的資料庫並非完整的資料庫。不過SnapManager 、您可以使用複製的資料庫來執行諸如建立設定檔和備份等動作、但SnapManager 由於複製的資料庫未設定為完整的資料庫、所以無法執行還原作業。
 a| 
恢復複製的資料庫、或將資料庫轉換成Data Guard待命資料庫。

|===


== 與還原程序相關的錯誤訊息（3000系列）

下表顯示與還原程序相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-03031：由於備份的儲存資源已經釋出、因此還原規格是還原備份所需的。」
 a| 
您嘗試還原已釋出儲存資源的備份、但未指定還原規格。
 a| 
指定還原規格。



 a| 
「MSAP-03032：還原規格必須包含要還原的檔案對應、因為備份的儲存資源已經釋出。需要對應的檔案為：<variable> from Snapshots:<variable>`
 a| 
您嘗試還原的備份已釋放其儲存資源、以及不包含所有要還原之檔案對應的還原規格。
 a| 
更正還原規格檔案、使對應符合要還原的檔案。



 a| 
「Oracle-30028：無法傾印記錄檔。檔案可能遺失/無法存取/毀損。此記錄檔將不會用於恢復。
 a| 
線上重作記錄檔或歸檔記錄檔無法用於還原。發生此錯誤的原因如下：

* 錯誤訊息中提及的線上重作記錄檔或歸檔記錄檔沒有足夠的變更編號可申請還原。當資料庫在線上且無任何交易時、就會發生這種情況。重作記錄或歸檔記錄檔沒有任何可套用至還原的有效變更編號。
* 錯誤訊息中提及的線上重作記錄檔或歸檔記錄檔、沒有足夠的Oracle存取權限。
* 錯誤訊息中提及的線上重作記錄檔或歸檔記錄檔已毀損、Oracle無法讀取。
* 錯誤訊息中提及的線上重作記錄檔或歸檔記錄檔、在所述路徑中找不到。

 a| 
如果錯誤訊息中提及的檔案是歸檔的記錄檔、而且您已手動提供恢復功能、請確定該檔案具有Oracle的完整存取權限。即使檔案具有完整權限、 而且訊息會繼續顯示、歸檔記錄檔沒有任何變更編號可套用至恢復、而且此訊息可以忽略。

|===


== 與複製程序相關的錯誤訊息（4000系列）

下表顯示與複製程序相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-04133：傾印目的地不可存在」
 a| 
您使用SnapManager 的是功能表來建立新的複本、不過新複本所使用的傾印目的地已經存在。如果存在傾印目的地、則無法建立實體複本。SnapManager
 a| 
在建立複本之前、請先移除或重新命名舊的傾印目的地。



 a| 
「MSAP-13032：無法執行作業：建立實體複本。根本原因：Oracle-00001：執行SQL時發生錯誤：[Alter database OPEN RESETLOGS；]。傳回的命令：ora-38856：無法將執行個體未命名的_instance_2（重作執行緒2）標記為已啟用。
 a| 
當您使用下列設定從待命資料庫建立複本時、複本建立將會失敗：

* 待命模式是使用RMAN來進行資料檔案備份。

 a| 
在建立實體複本之前、請先在實體複本規格檔案中新增「_no_recovery _top_resettlogs=true」參數。如需其他資訊、請參閱Oracle文件（ID 334899.1）。請確定您擁有Oracle Metalink使用者名稱和密碼。



 a| 
 a| 
您未在Clone規格檔案中提供參數值。
 a| 
您必須為參數提供值、或是在複製規格檔案中不需要時刪除該參數。

|===


== 與管理設定檔程序相關的錯誤訊息（5000系列）

下表顯示與複製程序相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-20600：在儲存庫「repo_name」中找不到設定檔「profile1」。請執行「設定檔同步」以更新設定檔對儲存庫的對應。
 a| 
當設定檔建立失敗時、就無法執行傾印作業。
 a| 
使用「msap系統傾印」。

|===


== 與釋出備份資源相關的錯誤訊息（備份6000系列）

下表顯示與備份工作相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-06030：無法移除備份、因為備份正在使用中：<variable>」
 a| 
當備份掛載或標記為無限保留時、您嘗試使用命令執行備份空閒作業。
 a| 
卸載備份或變更無限保留原則。如果存在複本、請刪除複本。



 a| 
「MSAP-06045：無法釋出備份<variable>、因為備份的儲存資源已經釋出」
 a| 
當備份已釋出時、您嘗試使用命令執行備份空閒作業。
 a| 
如果備份已經釋放、您就無法將其釋放。



 a| 
「MSAP-06047：只有成功的備份可以釋出。備份<ID>的狀態為<STATUS>'。
 a| 
當備份狀態不成功時、您嘗試使用命令執行備份空閒作業。
 a| 
成功備份後再試一次。



 a| 
「MSAP-13082：無法在備份<ID>上執行作業<variable>、因為備份的儲存資源已經釋出」。
 a| 
使用命令時、您嘗試掛載已釋出其儲存資源的備份。
 a| 
您無法在已釋出儲存資源的備份上掛載、複製、驗證或執行回溯還原。

|===


== 與循環升級程序（9000系列）相關的錯誤訊息

下表顯示與循環升級程序相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-09234：舊儲存庫中不存在下列主機。<主機名稱>。
 a| 
您嘗試執行主機的循環升級、舊版儲存庫不存在此功能。
 a| 
使用SnapManager 舊版的整套指令「儲存庫show-reposac儲存 庫」、檢查主機是否存在於舊版的儲存庫中。



 a| 
「MSAP-09255：新儲存庫中不存在下列主機。<主機名稱>。
 a| 
您嘗試執行主機回溯、但新儲存庫版本中並不存在此功能。
 a| 
使用SnapManager 更新版本的整套CLI中的「儲存庫show-repository」命令、檢查主機是否存在於新儲存庫中。



 a| 
「MSAP-09256：不支援回溯、因為有指定主機的新設定檔<profilenames>.'。
 a| 
您嘗試復原儲存庫中現有新設定檔的主機。不過、這些設定檔並不存在於舊SnapManager 版的主機上。
 a| 
在復原之前刪除更新版本SnapManager 或更新版本的更新版本的更新設定檔。



 a| 
「SAP-09257：不支援回溯、因為新主機上已掛載備份<backupid>。」
 a| 
您嘗試回復SnapManager 裝有備份的更新版本的支援。這些備份不會安裝在SnapManager 舊版的支援主機上。
 a| 
卸載SnapManager 更新版本的還原主機中的備份、然後執行復原。



 a| 
「SAP-09258：不支援回溯、因為新主機中的備份<backupid>已卸載。」
 a| 
您嘗試回溯SnapManager 更新版本的支援正在卸載備份的支援功能。
 a| 
將備份掛載SnapManager 到更新版本的支援主機中、然後執行復原。



 a| 
「MSAP-09298：無法更新此儲存庫、因為其較高版本中已有其他主機。請改為針對所有主機執行全方位升級。
 a| 
您在單一主機上執行循環升級、然後更新該主機的儲存庫。
 a| 
在所有主機上執行循環升級。



 a| 
「MSAP-09297:啟用限制時發生錯誤。儲存庫可能處於不一致狀態。建議還原您在目前作業之前所進行的儲存庫備份。
 a| 
如果儲存庫資料庫處於不一致狀態、您嘗試執行循環升級或復原作業。
 a| 
還原先前備份的儲存庫。

|===


== 執行作業（12、000系列）

下表顯示與作業相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-12347 [ERROR]：SnapManager 無法在主機和連接埠上執行支援服務器。請在執行SnapManager 此功能的主機上執行此命令。
 a| 
設定設定檔時、您輸入了有關主機和連接埠的資訊。不過SnapManager 、由於SnapManager 無法在指定的主機和連接埠上執行支援、所以無法執行這些作業。
 a| 
在執行SnapManager 支援服務器的主機上輸入命令。您可以使用「lsnrctl STATUS」命令來檢查連接埠、並查看資料庫執行所在的連接埠。如有需要、請在備份命令中變更連接埠。

|===


== 執行程序元件（13、000系列）

下表顯示SnapManager 與流程元件有關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「SAP-13083：Snapname模式的值為「x」、包含字母、數字、底線、破折號和大括弧以外的字元」。
 a| 
建立設定檔時、您已自訂Snapname模式；不過、您包含了不允許的特殊字元。
 a| 
移除字母、數字、底線、破折號和大括弧以外的特殊字元。



 a| 
「SAP-13084：使用「x」值的Snapname模式不包含相同數量的左右大括弧」。
 a| 
建立設定檔時、您已自訂Snapname模式、但左、右大括弧不相符。
 a| 
在Snapname模式中輸入相符的左方括弧和右方括弧。



 a| 
「MSAP-13085：Snapname模式的值為「x」、其中含有無效的變數名稱「y」。
 a| 
建立設定檔時、您已自訂Snapname模式；不過、您包含了不允許的變數。
 a| 
移除有問題的變數。若要查看可接受變數的清單、請參閱 xref:concept-snapshot-copy-naming.adoc[Snapshot複本命名]。



 a| 
值為「x」的「SMSAP-13086 Snapname模式」必須包含變數「SMID」。
 a| 
建立設定檔時、您已自訂Snapname模式、但卻遺漏了必要的「中等」變數。
 a| 
插入所需的「中等」變數。

|===


== 與NetApp相關的錯誤訊息SnapManager （14、000系列）

下表顯示SnapManager 與之相關的常見錯誤：

|===
| 錯誤訊息 | 說明 | 解決方案 


 a| 
「MSAP-14501：郵件ID不可空白」。
 a| 
您未輸入電子郵件地址。
 a| 
輸入有效的電子郵件地址。



 a| 
「MSAP-14502：郵件主旨不可空白」。
 a| 
您未輸入電子郵件主旨。
 a| 
輸入適當的電子郵件主旨。



 a| 
「MSAP-14506：郵件伺服器欄位不可空白」。
 a| 
您未輸入電子郵件伺服器主機名稱或IP位址。
 a| 
輸入有效的郵件伺服器主機名稱或IP位址。



 a| 
「MSAP-14507：郵件連接埠欄位不可空白」。
 a| 
您未輸入電子郵件連接埠號碼。
 a| 
輸入電子郵件伺服器連接埠號碼。



 a| 
「MSAP-14508：寄件者郵件ID不可為空白」。
 a| 
您未輸入寄件者的電子郵件地址。
 a| 
輸入有效的寄件者電子郵件地址。



 a| 
「MSAP-14509：使用者名稱不能為空白」。
 a| 
您已啟用驗證、但未提供使用者名稱。
 a| 
輸入電子郵件驗證使用者名稱。



 a| 
「MSAP-14510：密碼不可空白。請輸入密碼。
 a| 
您已啟用驗證、但未提供密碼。
 a| 
輸入電子郵件驗證密碼。



 a| 
「MSAP-14550：電子郵件狀態<成功/失敗>」。
 a| 
連接埠號碼、郵件伺服器或接收者的電子郵件地址無效。
 a| 
在電子郵件組態期間提供適當的值。



 a| 
「MSAP-14559：傳送電子郵件通知失敗：<錯誤>」。
 a| 
這可能是因為無效的連接埠號碼、無效的郵件伺服器或無效的接收者郵件位址。
 a| 
在電子郵件組態期間提供適當的值。



 a| 
「MSAP-14560：通知失敗：通知組態無法使用」。
 a| 
通知傳送失敗、因為通知組態無法使用。
 a| 
新增通知組態。



 a| 
「MSAP-14465：時間格式無效。請輸入時間格式、以hh：mm'表示。
 a| 
您輸入的時間格式不正確。
 a| 
以下列格式輸入時間：hh：mm。



 a| 
「MSAP-14566：無效的日期值。有效日期範圍為1-31。
 a| 
設定的日期不正確。
 a| 
日期應介於1到31之間。



 a| 
「MSAP-1467：無效的日值。有效日期範圍為1-7'。
 a| 
設定的日期不正確。
 a| 
輸入1到7之間的天數範圍。



 a| 
「MSAP-14569：伺服器無法啟動摘要通知排程」。
 a| 
由於不明原因、導致該伺服SnapManager 器關機。
 a| 
啟動SnapManager 伺服器。



 a| 
「SAP-14570：無法取得摘要通知」。
 a| 
您尚未設定摘要通知。
 a| 
設定摘要通知。



 a| 
「MSAP-14571：無法啟用設定檔和摘要通知」。
 a| 
您已同時選取設定檔和摘要通知選項。
 a| 
啟用設定檔通知或摘要通知。



 a| 
「MSAP-14572：提供成功或失敗選項以供通知」。
 a| 
您尚未啟用成功或失敗選項。
 a| 
您必須選擇成功或失敗選項、或兩者皆選。

|===