---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: 此命令可讓您設定使用者存取安全資源（例如主機、儲存庫和資料庫設定檔）的認證。主機密碼是SnapManager 執行此功能的主機上的使用者密碼。儲存庫密碼是Oracle使用者的密碼、其中包含SnapManager 了這個儲存庫架構。設定檔密碼是由建立設定檔的人員所組成的密碼。對於主機和儲存庫選項、如果未包含選用的-password選項、系統會提示您輸入命令引數中指定類型的密碼。 
---
= smsap認證集命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此命令可讓您設定使用者存取安全資源（例如主機、儲存庫和資料庫設定檔）的認證。主機密碼是SnapManager 執行此功能的主機上的使用者密碼。儲存庫密碼是Oracle使用者的密碼、其中包含SnapManager 了這個儲存庫架構。設定檔密碼是由建立設定檔的人員所組成的密碼。對於主機和儲存庫選項、如果不包含選用的「密碼」選項、系統會提示您輸入命令引數中指定類型的密碼。



== 語法

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== 參數

* *（主機名稱）_hostname_`*
+
指定SnapManager 執行此功能的主機伺服器名稱或IP位址。

+
「-host'參數包括下列選項：

+
** he-name host_name：指定要設定密碼的主機名稱。
** -`usernameusernam_name'：指定主機上的使用者名稱。
** 密碼：指定主機上使用者的密碼。


* *系統儲存庫-dbname*
+
指定儲存設定檔的資料庫名稱。使用全域名稱或SID。

+
「-repository」參數包括下列選項：

+
** -`dbnamerepo_service_name：指定儲存設定檔的資料庫名稱。使用全域名稱或SID。
** 主機repo_host`：指定儲存庫資料庫執行所在主機伺服器的名稱或IP位址。
** -`-login-usernamerepo_username'：指定存取儲存庫資料庫所需的使用者名稱。
** 密碼：指定存取儲存庫資料庫所需的密碼。
** ‘-port repo_port'：指定用於存取儲存庫資料庫的TCP連接埠號碼。


* *。-profile -name _profile_name_`*
+
指定與資料庫相關聯的設定檔。

+
「-profile」參數包括下列選項：

+
** 名稱profileName：指定您要設定密碼的設定檔名稱。
** 密碼：指定存取設定檔所需的密碼。


* *（靜音）*
+
僅在主控台顯示錯誤訊息。預設為顯示錯誤和警告訊息。

* *（冗長）*
+
在主控台上顯示錯誤、警告和資訊訊息。





== 設定儲存庫認證的命令範例

下列範例設定儲存庫的認證資料。

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== 設定主機認證的命令範例

由於主機認證資料代表實際的作業系統認證資料、因此除了密碼外、還必須包含使用者名稱。

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----