---
permalink: windows/task-customize-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: 您可以在建立新設定檔時、針對其自訂電子郵件主旨。 
---
= 自訂新設定檔的電子郵件主旨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在建立新設定檔時、針對其自訂電子郵件主旨。



== 關於這項工作

您可以使用「｛profile｝_\｛operation-name｝_\｛db-sID｝_\｛db-host｝_\｛start-date｝_\｛end-date｝_\｛STATUS｝模式來自訂電子郵件主旨、或輸入您自己的文字。

|===
| 變數名稱 | 說明 | 範例值 


 a| 
《設定檔》
 a| 
用於資料庫作業的設定檔名稱
 a| 
PROF1



 a| 
「營運名稱」
 a| 
資料庫作業名稱
 a| 
備份、資料備份、資料與歸檔記錄備份



 a| 
「Db-SID」
 a| 
資料庫的SID
 a| 
DB1



 a| 
「Db-host」
 a| 
主機伺服器名稱
 a| 
主機A



 a| 
「開始日期」
 a| 
以mmdd:hhh：s yyyy格式執行資料庫作業的開始時間
 a| 
2012年4月27日21：00：45（太平洋標準時間2012年）



 a| 
「結束日期」
 a| 
以mmdd:hhh：s yyyy格式結束資料庫作業時間
 a| 
2012年4月27日21：10：45（太平洋標準時間2012年）



 a| 
狀態
 a| 
資料庫作業狀態
 a| 
成功

|===
如果您未提供任何變數值、SnapManager 則Sing會顯示下列錯誤訊息：「Missing Value(s)-Subject」（顯示值-主旨）。

.步驟
. 輸入下列命令：
+
_smsap profile create -profile _profile_[-profile-password _profile_password_]-reposit儲存 庫-dbname _repo_service_name_-host _repo_host_-port _repo_port_-login-username_-database-dbname _dbdbname_-host _db_host_[-hourly port_login_[-s_密碼_ened_deed_deed_deed_deed_deed_deed_stock_sthour_ms_ened_deed_deed_st_st_[_sthour_ened_deed_deed_deed_deed_deed_deed_deed_deed_dektAN _n_][-dim_m_][-每週[-count_n_][-持續時間_m_]][-每月[-count_n_][-duration _m_]][-comment _comment _][-snapname -Pattern_][-notification [-addresssure_email_email_1_主題電子郵件_主題_電子郵件_主題_電子郵件_主題_電子郵件_主題_主題_主題_電子郵件_


