---
permalink: windows/task-create-profiles.html 
sidebar: sidebar 
keywords: create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: 建立設定檔時、您可以將特定的Oracle資料庫使用者帳戶指派給設定檔。您可以設定設定檔的保留原則、並設定每個保留類別的保留計數和持續時間。 
---
= 建立設定檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立設定檔時、您可以將特定的Oracle資料庫使用者帳戶指派給設定檔。您可以設定設定檔的保留原則、並設定每個保留類別的保留計數和持續時間。



== 關於這項工作

如果您未提供資料庫的「-login'、「-password」和「-port」參數值、作業系統（OS）驗證模式會使用預設認證。

在建立設定檔時SnapManager 、執行還原資格檢查、以判斷可用來還原資料庫的還原機制。

使用支援（3.2或更新版本）、您可以在建立新設定檔或更新現有設定檔的同時、將歸檔記錄檔與資料檔分開。SnapManager使用設定檔分隔備份之後、您可以只建立資料庫的純資料檔案備份、或僅建立資料庫的記錄檔備份。您可以使用新的設定檔或更新的設定檔來建立包含資料檔案和歸檔記錄檔的備份。不過、您無法使用設定檔來建立完整備份或還原設定。

*用於建立完整和部分備份的設定檔*

您可以建立設定檔、以建立完整的資料庫備份、其中包含資料檔案、控制檔、歸檔記錄檔、以及包含指定資料檔案或表格空間、所有控制檔及所有歸檔記錄檔的部分資料庫備份。不允許使用為完整和部分備份所建立的設定檔來建立個別的歸檔記錄備份。SnapManager

*用於建立純資料檔案備份與僅歸檔程式備份的設定檔*

當您建立新的設定檔時、可以加入「分離式歸檔儲存記錄備份」、將歸檔記錄備份與資料檔案備份區分開。您也可以更新現有的設定檔、將歸檔記錄備份與資料檔案備份分開。

透過使用新的設定檔選項來分隔歸檔記錄備份、您可以執行下列SnapManager 功能：

* 建立歸檔記錄備份
* 刪除歸檔記錄備份
* 掛載歸檔記錄備份
* 釋放歸檔記錄備份


建立設定檔以將歸檔記錄備份與資料檔案備份分開時、如果建立設定檔的資料庫中不存在歸檔記錄檔、則會顯示警告訊息。


WARNING: 「歸檔的記錄檔不存在於作用中的檔案系統中。備份中不會包含<歸檔記錄執行緒版本>記錄檔之前的歸檔記錄檔版本

即使您為此資料庫建立備份、歸檔記錄檔仍無法在資料庫備份中使用。


NOTE: 如果在建立設定檔時遇到錯誤、請使用「shmsap system dump」命令。建立設定檔之後、如果發生錯誤、請使用「msap operation dump」和「shmsap profile dump」命令。

.步驟
. 若要建立使用者名稱、密碼和連接埠（Oracle驗證）的設定檔、請輸入下列命令：
+
hy*smsap profile create -profileprofile [-profile-passwordsprofile_password]-reposite-dbnamerepo_dbname-hovernpo_host-addressrepo_port-login-usernameraddressepo_username-database-dbnamedb_dbnameddbnameddb_host [-siddb_siddb_siddb_sidb_sid_sid][-loggarm/usernamed_dep_noteeparm/noteep_noteep_noteep_noteep-tamed[-pure-noteeparm/noteeparam_deepsite-noteepsepsepse_noteepse_noteepsite-noteepam_depam_deparamed[-noteepam_depam_deparamedamed][-pampaelm_samedamedamedamed][-peepam_depamedamedamedam_depam_depam_deparam_deparamed][-

+
此命令的其他選項如下：

+
[`-force（力量）][`-nosmp]

+
['quide'|'verbose']

+
根據您要存取資料庫的方式、您也可以在建立設定檔時加入其他選項。

+
|===
| 如果... | 然後... 


 a| 
*您想要使用資料庫驗證來建立設定檔*
 a| 
指定資料庫登入詳細資料。



 a| 
*您想要指定備份保留原則*
 a| 
指定保留類別的保留計數或持續時間、或兩者。持續時間以課程單位為單位（例如小時、日）。

** 「每小時」是指每小時保留班數、其中「單位數n」（「單位持續時間m」）分別為保留期間數和保留期間。
** 「每日」是指每日保留類別、其中「記錄n」（）「持續時間m」（）分別是保留次數和保留時間。
** 「每週」是每週保留課程、其中的「持續時間」分別為保留次數和保留時間。
** 「每月」是指每月保留等級、其中「記錄n」（）「持續時間m」（）分別為保留天數和保留期間。




 a| 
*您想要啟用資料庫作業完成狀態的電子郵件通知*
 a| 
指定下列選項和變數：

** 「摘要通知」可讓您針對儲存庫資料庫下的多個設定檔設定摘要電子郵件通知。
** 「通知」可讓您收到電子郵件通知、告知設定檔資料庫作業的完成狀態。
** 您可以使用新的或現有的設定檔、接收關於資料庫作業成功的電子郵件通知。
** 您可以使用新的或現有的設定檔、接收有關資料庫作業失敗的電子郵件通知。
** 在建立新的設定檔或現有設定檔時、「SubectSub_text_text」會指定電子郵件通知的主旨文字。如果通知設定未針對儲存庫進行設定、而您嘗試使用CLI設定設定設定檔或摘要通知、則主控台記錄中會記錄下列訊息：「MSAP-1477: Notification Settings Not Configure（通知設定未設定）」。
+
如果您已設定通知設定、並嘗試使用CLI設定摘要通知、但未啟用儲存庫的摘要通知、則主控台記錄中會顯示下列訊息：「MSAP-14775：摘要通知組態無法用於此儲存庫」





 a| 
*您想要將歸檔記錄檔與資料檔分開備份*
 a| 
指定下列選項和變數：

** 「分隔的archivelog-Backup」可讓您將歸檔記錄備份與資料檔案備份分開。
** 「-ret-archivelog-Backups」可設定歸檔記錄備份的保留時間。您必須指定正的保留期間。
+
歸檔記錄備份會根據歸檔記錄保留期間而保留。資料檔案備份會根據現有的保留原則來保留。

** 「包括線上備份」包括歸檔記錄備份、以及線上資料庫備份。
+
此選項可讓您一起建立線上資料檔案備份與歸檔記錄備份、以便進行複製。設定此選項時、每當您建立線上資料檔案備份時、都會立即建立歸檔記錄備份及資料檔案。

** 「不含線上備份」不包括歸檔記錄備份與資料庫備份。




 a| 
*您可以在設定檔成功建立作業之後收集傾印檔*
 a| 
在「profile create」命令結尾處指定「-dump」選項。

|===

