---
permalink: windows/task-customizing-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: 您可以在建立新設定檔時、針對其自訂電子郵件主旨。 
---
= 自訂新設定檔的電子郵件主旨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在建立新設定檔時、針對其自訂電子郵件主旨。

您可以使用「｛profile｝_\｛operation-name｝_\｛db-sID｝_\｛db-host｝_\｛start-date｝_\｛end-date｝_\｛STATUS｝模式來自訂電子郵件主旨、或輸入您自己的文字。

|===
| 變數名稱 | 說明 | 範例值 


 a| 
設定檔
 a| 
用於資料庫作業的設定檔名稱
 a| 
PROF1



 a| 
作業名稱
 a| 
資料庫作業名稱
 a| 
備份、資料備份、資料與歸檔記錄備份



 a| 
DB-SID
 a| 
資料庫的SID
 a| 
DB1



 a| 
DB-主機
 a| 
主機伺服器名稱
 a| 
主機A



 a| 
開始日期
 a| 
以mmdd:hhh：s yyyy格式執行資料庫作業的開始時間
 a| 
2012年4月27日21：00：45（太平洋標準時間2012年）



 a| 
結束日期
 a| 
以mmdd:hhh：s yyyy格式結束資料庫作業時間
 a| 
2012年4月27日21：10：45（太平洋標準時間2012年）



 a| 
狀態
 a| 
資料庫作業狀態
 a| 
成功

|===
如果您未提供任何變數值、SnapManager 則Sing會顯示下列錯誤訊息：Missing Value（s）-Subject。

. 輸入下列命令：
+
msap profile create -profileprofile [-profile-password-profile_password]-reposite-dbnamerepo_service_name-hovampo_host-portrepo_port-login-usernameraddressepo_username-database-dbnamedb_dbname-hostPatterndb_host [-siddb_siddb_sid][-login_usernamedamedfailsepam_dep-tream_deparam_note_noteep-tream[-phour-pour-peck_noteeparam_noteeparam_noteepam_pass_pass_pass_noteepam_noteepam_deep_pass_pass_pass_pass_pass_pass_noteepam_depam_noteepam_noteepam_[-tream_deepam_un][-pyour][-pyour][-tream_noteeparam_noteepam_noteepamed[-pyour][-pyour][-pyour][


