---
permalink: windows/task-restore-backups-on-primary-storage.html 
sidebar: sidebar 
keywords: backup, restore, command, database, primary, storage 
summary: 您可以使用備份還原命令、在主要儲存設備上還原資料庫備份。 
---
= 還原主儲存設備上的備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「備份還原」命令、在主要儲存設備上還原資料庫備份。



== 關於這項工作

您可以使用「備份還原」命令選項來指定SnapManager 恢復全部或部分備份。利用此功能、您也可以在單一使用者作業中、從備份中還原控制檔、以及資料檔案或表格空間。SnapManager您可以將「-controlFiles」與「-complete」一起納入、以還原控制檔、以及表格空間和資料檔案。

您可以選取下列其中一個選項來還原備份：

[cols="1a,1a"]
|===
| 如果您要還原... | 使用... 


 a| 
完整備份、包含所有表格空間和資料檔案
 a| 
「完整」



 a| 
特定資料表空間的清單
 a| 
「表格空間」



 a| 
特定資料檔案
 a| 
文件



 a| 
僅控制檔
 a| 
控制檔



 a| 
表格空間、資料檔案及控制檔
 a| 
完整的「控制檔」

|===
您也可以指定「-restoresespec」、從替代位置還原備份。

如果包含「-recover'」、您可以將資料庫恢復至：

* 資料庫中發生的最後一筆交易（所有記錄）
* 特定日期與時間
* 特定Oracle系統變更編號（SCN）
* 備份時間（無記錄）
* 僅還原



NOTE: 日期和時間恢復和SCN恢復都是時間點恢復。

利用歸檔記錄檔、即可自動恢復還原的資料庫備份（3.2或更新版本）SnapManager 。即使外部位置有歸檔記錄檔、如果您指定「-recover-from -location」選項、SnapManager 則會使用外部位置的歸檔記錄檔來恢復還原的資料庫備份。

當您指定外部歸檔記錄位置來還原還原的備份時、必須確保以大寫輸入外部位置名稱。在檔案系統中、所有的資料夾和子資料夾名稱都必須是大寫、因為Oracle會將目的地路徑轉譯為大寫、並預期外部目的地路徑、資料夾名稱和子資料夾名稱會是大寫。如果您以小寫形式指定外部歸檔記錄目的地路徑、Oracle可能無法識別指定的路徑、也無法還原資料庫。

支援Oracle的外部位置。SnapManager但Oracle無法識別來自外部目的地的檔案。Flash恢復區域目的地會注意到這種行為。這些都是Oracle的問題、因應措施是永遠在這類資料庫配置中備份歸檔記錄檔。

如果提供任何不一致的SCN或日期、則恢復作業將會在恢復的最後一個一致點停止、並顯示錯誤訊息「Recovery成功、但不足」。您必須手動將恢復作業恢復至一致的狀態。

為了在沒有套用記錄的情況下恢復、SnapManager 直到上次在備份期間建立的歸檔記錄檔最後一次SCN為止、即可恢復。如果資料庫在此次SCN之前一致、則資料庫將成功開啟。如果此時資料庫不一致、SnapManager 則如果資料庫已經一致、則可能會嘗試開啟資料庫、而資料庫將成功開啟。


NOTE: 不支援還原歸檔記錄專用備份。SnapManager

如果歸檔記錄目的地不是支援Snapshot的儲存設備、SnapManager 則可使用設定檔恢復還原的資料庫備份。在不具備Snapshot功能的儲存設備上執行SnapManager 支援功能的操作之前、您應該在「smsap.config」中新增「archivedLogs.exclude」的目的地。

在建立設定檔之前、您必須先設定exclude參數。只有在SnapManager 將exclude參數設定為包含在實體組態檔案中之後、設定檔才會成功建立。

如果備份已經掛載、SnapManager 則不會再次掛載備份、並使用已掛載的備份。如果備份是由不同的使用者掛載、而且目前的使用者無法存取先前掛載的備份、則其他使用者必須提供權限。所有的歸檔記錄檔都具有群組擁有者的讀取權限；如果備份是由不同的使用者群組掛載、則目前的使用者可能無法取得權限。使用者可以手動授予已掛載歸檔記錄檔的權限、然後重試還原或還原。

您可以將「-dump」選項指定為選用參數、以便在還原作業成功或失敗後收集傾印檔案。

.步驟
. 輸入下列命令：
+
h.*smsap備份還原-profile _profile_name_-label _-f完整-recover-alllogs [-recover-from位置_path_[,_path2_]-dump - verbose*

+
* 範例 *

+
「* smsap備份還原-profile目標db1_rof1 -label full _bkup_sales_nov_08 -完整-復原-alllogs -verbose*」

. 若要還原不同案例的資料、請完成下列其中一項：
+
[cols="1a,1a"]
|===
| 如果您要還原... | 命令範例 


 a| 
不需控制檔案即可完成資料庫、並恢復至特定的SCN編號（3794392）。在這種情況下、目前的控制檔存在、但所有的資料檔都已毀損或遺失。將資料庫從現有的完整線上備份還原並還原至SCN之前的某個點。
 a| 
`*smsap備份還原-profile目標db1_rof1 -label full _bkup_sales_nov_08 -full -recoving -直到3794392 -verbose*



 a| 
不需控制檔案就能完成資料庫、並恢復到最新的時間。
 a| 
「* smsap備份還原-設定檔目標db1_rof1 -標籤Full_bkup_sales_nov_08 -完整-恢復-直到2008-09-15：15：29：23 - verbose*」



 a| 
不需控制檔案即可完成資料庫、並可恢復至資料與時間。在這種情況下、目前的控制檔存在、但所有的資料檔都已毀損或遺失、或是在特定時間之後發生邏輯錯誤。將資料庫從現有的完整線上備份還原至故障點之前的日期與時間。
 a| 
'*smsap備份還原-profile目標db1_rof1 -label full _bkup_sales_nov_08 -full -recover-fuse -直到"2008-09-15:15:29:23"-verbose*



 a| 
部分資料庫（一或多個資料檔案）、不含控制檔、並使用所有可用記錄進行還原。在這種情況下、目前的控制檔存在、但有一或多個資料檔已毀損或遺失。使用所有可用的記錄、還原這些資料檔案、並從現有的完整線上備份中恢復資料庫。
 a| 
h.*smsap備份還原-profile目標db1_rof1 -標籤full _bkup_sales_nov_08 -檔案E：\disks\S02．dbf E：\disks\sales03．dbf E：\disks\sales04．dbf - recoverclose -alllogs -verbos*



 a| 
部分資料庫（一或多個表格空間）、不含控制檔、並使用所有可用的記錄進行還原。在這種情況下、目前的控制檔存在、但會捨棄一或多個資料表空間、或是屬於資料表空間的多個資料檔之一毀損或遺失。使用所有可用的記錄、還原這些表格空間、並從現有的完整線上備份中還原資料庫。
 a| 
「* smsap備份還原-設定檔目標db1_rof1 -標籤Full_bkup_sales_nov_08 -表格空間使用者- recover-alllogs -verbose*」



 a| 
只能使用所有可用的記錄來控制檔案和恢復。在這種情況下、資料檔案存在、但所有控制檔都已毀損或遺失。只還原控制檔、並使用所有可用的記錄、從現有的完整線上備份中還原資料庫。
 a| 
`*smsap備份還原-profile目標db1_rof1 -標籤Full_bkup_sales_nov_08 - controlfile - recover-alllogs -verbose*



 a| 
不需控制檔案就能完成資料庫、並使用備份控制檔和所有可用記錄進行還原。在這種情況下、所有資料檔案都會毀損或遺失。只還原控制檔、並使用所有可用的記錄、從現有的完整線上備份中還原資料庫。
 a| 
「* smsap備份還原-profile目標db1_rof1 -標籤Full_bkup_sales_nov_08 -完整-使用備份控制檔- recoverclose -alllogs -verbose*」



 a| 
使用外部歸檔記錄位置的歸檔記錄檔來還原還原的資料庫。
 a| 
「* smsap備份還原-設定檔目標db1_rof1 -標籤Full_bkup_sales_nov_08 -完整-使用備份控制檔-復原-alllogs -從位置E:\\archive -verbose*」

|===
. 使用「-recover-from location」選項指定外部歸檔記錄位置。

