---
permalink: unix-administration/concept-fast-restore-eligibility-checks.html 
sidebar: sidebar 
keywords: perform, restore, backup, snapmanager, eligibility, check, fast 
summary: 當您選擇快速還原備份時、SnapManager 首先執行資格檢查、以判斷是否可以使用快速還原程序。 
---
= 快速還原資格檢查
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您選擇快速還原備份時、SnapManager 首先執行資格檢查、以判斷是否可以使用快速還原程序。

支援下列檢查類型：SnapManager

* 強制檢查：SnapManager 唯有在此檢查通過的所有條件下、才能執行快速還原程序。
* 可過度使用的檢查：如果此檢查條件失敗、系統管理員可以覆寫檢查以強制進行快速還原程序。不過、您必須謹慎置換這些檢查。


下表列出您可能遇到的問題、並指出是否可以覆寫快速還原資格檢查：

|===
| 問題 | 需要通過 | 詳細資料 


 a| 
ACFS、投票磁碟或OCRTM存在於11gR2的ASM磁碟群組中
 a| 
是的
 a| 
無法執行快速還原。解決方案：無

無法置換。



 a| 
只有SnapManager 使用支援更新版本的更新版本才能快速還原
 a| 
是的
 a| 
無法置換。



 a| 
只有使用SnapDrive 適用於UNIX 4.0或更新版本的Snapshot複本才能快速還原
 a| 
是的
 a| 
無法置換。



 a| 
Volume是根Volume
 a| 
是的
 a| 
正在還原的磁碟區是儲存系統上的根磁碟區。解決方案：請勿在儲存系統上使用根磁碟區。

無法置換。



 a| 
Volume還原在Windows上無法使用
 a| 
是的
 a| 
正在還原的磁碟區是儲存系統上的根磁碟區。解決方案：無

無法置換。



 a| 
Volume還原已停用
 a| 
是的
 a| 
Volume還原已停用。解決方案：啟動還原時、請選取不同的選項來啟用Volume還原。在命令列介面中、請勿使用「-fast -Off」。

無法置換。



 a| 
控制相同磁碟區上的檔案和資料檔案
 a| 
是的
 a| 
對於線上備份、控制檔和資料檔不能位於同一個磁碟區、因為SnapManager 它會取得兩個磁碟區的Snapshot複本（其中一個資料檔在熱備份模式下是一致的）。 以及在熱備份模式完成後、備份控制檔保持一致的狀態）。Volume還原會還原至第一個Snapshot複本、刪除包含備份控制檔的第二個Snapshot複本。發生純資料檔案還原時、控制檔會還原為不一致的狀態、SnapManager 且還原備份控制檔、然後使用「重新設定記錄」選項開啟資料庫、這是不想要的行為。

解決方案：將控制檔和資料檔案移轉到不共用相同基礎Volume的個別檔案系統。這對檢查失敗的還原沒有幫助、但有助於未來的備份還原作業。

無法置換。



 a| 
歸檔記錄和資料檔案不得存在於同一個磁碟區
 a| 
是的
 a| 
資料庫歸檔記錄和資料檔案位於以相同儲存系統磁碟區為後盾的檔案系統中。如果執行Volume還原、SnapManager 則還原線上備份後、無法開啟資料庫、因為資料庫從熱備份模式中取出後所寫入的歸檔記錄檔無法使用。此外、您也無法在歸檔記錄檔中的後續交易中進行轉寄。

解決方案：將歸檔記錄和資料檔案移轉到不共用相同基礎儲存系統磁碟區的個別檔案系統。這對檢查失敗的還原沒有幫助、但有助於未來的備份還原作業。

無法置換。



 a| 
線上記錄檔和資料檔案不得存在於同一個磁碟區
 a| 
是的
 a| 
資料庫線上重作記錄和資料檔案位於以相同儲存系統磁碟區為後盾的檔案系統中。如果執行了Volume還原、則恢復將無法使用線上重作記錄、因為這些記錄已還原。

解決方案：將線上重作記錄和資料檔案移轉到不共用相同基礎儲存系統磁碟區的個別檔案系統。這對檢查失敗的還原沒有幫助、但有助於未來的備份還原作業。

無法置換。



 a| 
檔案系統中不屬於還原範圍的檔案會還原
 a| 
是的
 a| 
除了要還原的檔案之外、主機上可見的檔案存在於磁碟區的檔案系統中。如果執行快速還原或儲存端檔案系統還原、則在建立Snapshot複本時、主機上可見的檔案會還原成原始內容。如果找到20個或更少檔案、則會在資格檢查中列出。SnapManager否則SnapManager 、將會顯示您應調查檔案系統的訊息。

解決方案：將資料庫未使用的檔案移轉到使用不同磁碟區的不同檔案系統。或者、也可以刪除檔案。

如果SnapManager 無法判斷檔案用途、您可以置換檢查失敗。如果您覆寫檢查、則不會在還原範圍內的檔案會還原。只有當您確定還原檔案不會對任何內容造成不良影響時、才可覆寫此檢查。



 a| 
將會還原指定Volume群組中不屬於還原範圍的檔案系統
 a| 
否
 a| 
多個檔案系統位於同一個Volume群組中、但並非所有檔案系統都會被要求還原。儲存端檔案系統還原與快速還原無法用於還原磁碟區群組內的個別檔案系統、因為磁碟區群組所使用的LUN包含來自所有檔案系統的資料。磁碟區群組中的所有檔案系統必須同時還原、才能使用快速還原或儲存設備端檔案系統還原。如果找到20個或更少檔案、請在資格檢查中列出這些檔案。SnapManager SnapManager否則SnapManager 、支援功能會提供您應調查檔案系統的訊息。

解決方案：將資料庫未使用的檔案移轉到不同的Volume群組。或者、也可以刪除Volume群組中的檔案系統。

可以置換。



 a| 
將會還原指定Volume群組中不屬於還原範圍的主機磁碟區
 a| 
否
 a| 
多個主機磁碟區（邏輯磁碟區）位於同一個磁碟區群組中、但並非所有的主機磁碟區都會被要求還原。這項檢查類似於磁碟區群組中的檔案系統、而非還原範圍的一部分、只是磁碟區群組中的其他主機磁碟區並未作為主機上的檔案系統掛載。解決方案：將資料庫使用的主機磁碟區移轉到不同的磁碟區群組。或者、刪除Volume群組中的其他主機磁碟區。

如果您覆寫檢查、則會還原Volume群組中的所有主機磁碟區。只有當您確定還原其他主機磁碟區不會對任何內容造成不良影響時、才可覆寫此檢查。



 a| 
自上次備份以來、檔案範圍已變更
 a| 
是的
 a| 
無法置換。



 a| 
磁碟區中未納入還原範圍的對應LUN將會還原
 a| 
是的
 a| 
除了要求在磁碟區中還原的LUN之外、目前還會對應到主機。無法執行磁碟區還原、因為使用這些LUN的其他主機或應用程式會變得不穩定。如果LUN名稱結尾為底線和整數索引（例如_0或_1）、則這些LUN通常是同一個磁碟區內其他LUN的複製。可能會掛載資料庫的另一個備份、或是存在另一個備份的複本。

解決方案：將資料庫未使用的LUN移轉到不同的磁碟區。如果對應的LUN是複製、請尋找已掛載的資料庫備份或資料庫複本、然後卸載備份或移除複本。

無法置換。



 a| 
磁碟區中未對應的LUN不屬於還原範圍的一部分、將會還原
 a| 
否
 a| 
除了要求在磁碟區中還原的LUN之外、還有其他LUN。這些LUN目前並未對應至任何主機、因此還原它們不會中斷任何作用中的處理程序。不過、LUN可能會暫時取消對應。解決方案：將資料庫未使用的LUN移轉到不同的磁碟區、或刪除LUN。

如果您置換此檢查、磁碟區還原會將這些LUN還原至Snapshot複本的建立狀態。如果在製作Snapshot複本時LUN不存在、則在磁碟區還原之後LUN將不存在。只有當您確定還原LUN不會對任何項目造成不良影響時、才可覆寫此檢查。



 a| 
磁碟區Snapshot複本中的LUN在還原時可能不一致
 a| 
否
 a| 
在Snapshot複本建立期間、磁碟區中存在未要求Snapshot複本的LUN。這些其他LUN的狀態可能不一致。解決方案：將資料庫未使用的LUN移轉到不同的磁碟區、或刪除LUN。這對檢查失敗的還原程序並無幫助、但有助於還原在移動或刪除LUN之後所進行的未來備份。

如果您覆寫此檢查、LUN會還原為建立Snapshot複本的不一致狀態。只有當您確定還原LUN不會對任何項目造成不良影響時、才可覆寫此檢查。



 a| 
新的Snapshot複本具有Volume Clone
 a| 
是的
 a| 
已建立Snapshot複本的複本複本、這些複本是在要求還原Snapshot複本之後建立的。由於Volume還原會刪除稍後的Snapshot複本、而且如果Snapshot複本具有複本、則無法刪除、因此無法執行Volume還原。解決方法：刪除後續Snapshot複本的複本。

無法置換。



 a| 
安裝較新的備份
 a| 
是的
 a| 
備份還原之後所進行的備份會掛載。由於Volume還原會刪除後續的Snapshot複本、因此如果Snapshot複本具有複製、備份掛載作業會建立複製的儲存設備、而且無法執行Volume還原。解決方案：卸載較新的備份、或從掛載備份後所進行的備份還原。

無法置換。



 a| 
存在較新備份的複本
 a| 
是的
 a| 
備份還原後所進行的備份已複製完成。由於Volume還原會刪除稍後的Snapshot複本、而且如果Snapshot複本有實體複本、則無法刪除該複本、因此無法執行Volume還原。解決方案：刪除較新備份的複本、或是從備份複本之後所進行的備份還原。

無法置換。



 a| 
磁碟區的新Snapshot複本遺失
 a| 
否
 a| 
執行磁碟區還原會刪除在磁碟區還原至的Snapshot複本之後所建立的所有Snapshot複本。如果SnapManager 使用同SnapManager 一個設定檔、能夠將稍後的Snapshot複本對應到某個還原備份、則會出現「較新的備份將被釋放或刪除」訊息。如果SnapManager 無法將稍後的Snapshot複本對應到SnapManager 同一個設定檔中的某個還原備份、則不會出現此訊息。解決方案：從稍後的備份還原、或刪除稍後的Snapshot複本。

可以置換。



 a| 
將會釋出或刪除較新的備份
 a| 
否
 a| 
執行Volume還原會刪除在將磁碟區還原至Snapshot複本之後所建立的所有Snapshot複本。因此、在備份之後建立的任何備份、都會被刪除或釋出。之後的備份會在下列案例中刪除：

* 備份狀態未受到保護
* 'reprec.alwaysFreeDecipiredBackups'在'shmsap.config'中是''*flash*


之後的備份會在下列案例中釋出：

* 備份狀態受到保護
* 'reprec.alwaysFreeDecipiredBackups'在'shmsap.config'中是真的'*假*


解決方案：從較新的備份還原、或是釋放或刪除較新的備份。

如果您覆寫此檢查、則會刪除或釋出正在還原的備份之後所建立的備份。



 a| 
磁碟區的SnapMirror關係會遺失
 a| 
是（如果已停用RBAC或您沒有RBAC權限）
 a| 
在SnapMirror關係中、將磁碟區還原至比基準Snapshot複本早的Snapshot複本、會破壞關係。解決方案：從關係的基礎Snapshot複本之後建立的備份還原。或者、您也可以手動中斷儲存關係（然後在還原完成後重新建立並重新建立關係基準）。

如果啟用RBAC且您具有RBAC權限、則可以置換。



 a| 
如果發生快速還原程序、磁碟區的關聯就會消失SnapVault
 a| 
是（如果已停用RBAC或您沒有RBAC權限）
 a| 
將磁碟區還原至比SnapVault 基礎Snapshot複本早的Snapshot複本、而這種關係會破壞關係。解決方案：從關係的基礎Snapshot複本之後建立的備份還原。或者、您也可以手動中斷儲存關係（然後在還原完成後重新建立並重新建立關係基準）。

如果啟用RBAC且您具有RBAC權限、則無法覆寫。



 a| 
磁碟區中非還原範圍一部分的NFS檔案會還原
 a| 
否
 a| 
如果執行Volume還原、儲存系統磁碟區中的檔案（在主機上看不到）會還原。解決方案：將資料庫未使用的檔案移轉到不同的磁碟區、或刪除檔案。

可以置換。如果您置換此檢查失敗、LUN將被刪除。



 a| 
適用於Volume的CIFS共享區存在
 a| 
否
 a| 
正在還原的磁碟區有CIFS共用區。在磁碟區還原期間、其他主機可能正在存取磁碟區中的檔案。解決方案：移除不需要的CIFS共用區。

可以置換。



 a| 
從替代位置還原
 a| 
是的
 a| 
針對還原作業提供還原規格、指定從替代位置還原檔案。只有主機端複製公用程式可用於從替代位置還原。

解決方案：無。

無法置換。



 a| 
RAC資料庫不支援儲存端檔案系統還原
 a| 
是的
 a| 
無法置換。

|===