---
permalink: unix-administration/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, operation, manage, managing, efficient 
summary: 您必須在SnapManager 還原中為要執行作業的資料庫建立設定檔。您必須選取設定檔、然後選取您要執行的作業。 
---
= 管理設定檔以有效備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須在SnapManager 還原中為要執行作業的資料庫建立設定檔。您必須選取設定檔、然後選取您要執行的作業。



== 與設定檔相關的工作

您可以執行下列工作：

* 建立設定檔、以便將完整或部分備份及備份至一線、二線或甚至三線儲存設備。
+
您也可以建立設定檔、將歸檔記錄備份與資料檔案備份分開。

* 驗證設定檔。
* 更新設定檔。
* 刪除設定檔。




== 關於設定檔與驗證

建立設定檔時、您可以指定資料庫、然後選擇下列其中一種方法來連線至資料庫：

* 使用使用者名稱、密碼和連接埠進行Oracle驗證
* 作業系統（OS）驗證、不含使用者名稱、密碼或連接埠。
+
若要進行OS驗證、您必須輸入OS帳戶使用者和群組資訊。

+

NOTE: 若要將OS驗證用於Real Application Cluster（RAC）資料庫、SnapManager 則必須在RAC環境的每個節點上執行此伺服器、且RAC環境中所有Oracle執行個體的資料庫密碼必須相同。使用資料庫使用者名稱和密碼連線至設定檔中的每個RAC執行個體。SnapManager

* 當「qlnet.authentication_services`」設定為「*無*」時、資料庫驗證。接著、將資料庫使用者名稱和密碼用於所有與目標資料庫的連線。SnapManager
+

NOTE: 若要針對自動儲存管理（ASM）執行個體使用資料庫驗證、您必須輸入用來登入ASM執行個體的使用者名稱和密碼。



您只能在下列環境中設定「qlnet.authentication_services`」為「* none*」：

[cols="1a,1a,1a,1a"]
|===
| 資料庫配置 | Oracle版本 | 目標資料庫是否支援資料庫驗證 | ASM執行個體是否支援資料庫驗證 


 a| 
任何非ASM和非RAC資料庫
 a| 
Oracle 10g與Oracle 11g（低於11.2.0.3）
 a| 
是的
 a| 
否



 a| 
UNIX上的獨立ASM資料庫
 a| 
Oracle 11.2.0.3及更新版本
 a| 
是的
 a| 
是的



 a| 
UNIX上RAC資料庫上的ASM執行個體
 a| 
Oracle 11.2.0.3
 a| 
否
 a| 
否



 a| 
NFS上的RAC資料庫
 a| 
Oracle 11.2.0.3
 a| 
是的
 a| 
否

|===

NOTE: 停用「qlnet.authentication_services`」並將驗證方法變更為資料庫驗證之後、您必須將「qlnet.authentication_services`」設定為「* none*」。

如果您是第一次存取設定檔、則必須輸入設定檔密碼。輸入認證資料之後、您就可以在設定檔中檢視資料庫備份。
