---
permalink: unix-administration/concept-database-backup-management.html 
sidebar: sidebar 
keywords: snapmanager, enable, data, local, storage, resource, post-processing, script, protect, secondary, tertiary, additional, layer, disaster, back, up, database 
summary: 使用後處理指令碼或保護二線或三線儲存資源上的備份、可以使用Snapshot Manager來備份本機儲存資源上的資料。備份到二線儲存設備的選擇、可提供額外的層級、在發生災難時保留資料。 
---
= 備份資料庫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
藉由保護二線或三線儲存資源上的備份、使用後處理指令碼處理、即可在本機儲存資源上備份資料。SnapManager備份到二線儲存設備的選擇、可提供額外的層級、在發生災難時保留資料。

此外、利用此功能、儲存管理員也能根據原則計畫來設定備份。SnapManager透過使用功能、系統管理員可以識別不符合原則要求的備份、並立即修正這些備份。SnapManager

支援下列選項來備份、還原及恢復資料庫中的資料：SnapManager

* 備份整個資料庫或其中一部分。
+
如果您備份其中一部分、請指定一組表格空間或一組資料檔案。

* 分別備份資料檔案和歸檔記錄檔。
* 將資料庫備份至一線儲存設備（也稱為本機儲存設備）、並將資料庫備份至二線或三線儲存設備（也稱為遠端儲存設備）以保護資料庫。
* 排程例行備份。


*功能不一樣（3.2版或更新版本）與舊版的功能不一樣* SnapManager SnapManager

利用支援（3.1或更早版本）的功能、您可以建立包含資料檔案、控制檔及歸檔記錄檔的完整資料庫備份。SnapManager

僅由（3.1或更早版本）管理資料檔案。SnapManager歸檔記錄檔是使用SnapManager 非功能表的解決方案來維護。

在管理資料庫備份時、使用下列限制條件（3.1或更早版本）SnapManager ：

* 效能影響
+
當您執行完整的線上資料庫備份（當資料庫處於備份模式時）時、資料庫的效能會在建立備份之前縮短一段時間。在32（3.2或更新版本）中SnapManager 、可以進行有限的資料庫備份和頻繁的歸檔記錄備份。頻繁進行歸檔記錄備份有助於防止資料庫置於備份模式。

* 手動還原與還原
+
當作用中檔案系統中不存在所需的歸檔記錄檔時、資料庫管理員必須識別哪些備份包含歸檔記錄檔、掛載資料庫備份、以及還原還原還原的資料庫。此程序相當耗時。

* 空間限制
+
建立資料庫備份時、歸檔記錄目的地會變滿、導致資料庫在儲存設備上建立足夠空間之前不會回應。在32（3.2或更新版本）中SnapManager 、可從作用中檔案系統剪除歸檔記錄檔、以定期釋出空間。



*歸檔記錄備份為何重要*

執行還原作業之後、需要將資料庫轉寄歸檔記錄檔。Oracle資料庫上的每筆交易都會擷取在歸檔記錄檔中（如果資料庫處於歸檔記錄模式）。資料庫管理員可以使用歸檔記錄檔來還原資料庫備份。

*僅歸檔程序備份的優點*

* 為僅歸檔日誌備份提供獨立的保留時間
+
您可以減少僅歸檔日誌備份的保留時間、而這是還原所需的時間。

* 根據歸檔記錄保護原則、保護僅歸檔記錄的備份
+
您可以根據歸檔工具專屬備份的需求、為其選取不同的保護原則。

* 改善資料庫效能
* 整合歸檔記錄備份
+
利用釋放重複的歸檔記錄備份、即可在每次進行備份時整合歸檔記錄備份。SnapManager


