---
permalink: unix-administration/concept-configuring-e-mail-notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, email, notification, completion, status, profile-executed, database, operation, configuring, configure 
summary: 利用此功能、您可以接收關於設定檔執行資料庫作業完成狀態的電子郵件通知。SnapManager系統會產生電子郵件、並根據資料庫作業完成狀態、協助您採取適當的行動。SnapManager設定電子郵件通知是選用參數。 
---
= 設定電子郵件通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用此功能、您可以接收關於設定檔執行資料庫作業完成狀態的電子郵件通知。SnapManager系統會產生電子郵件、並根據資料庫作業完成狀態、協助您採取適當的行動。SnapManager設定電子郵件通知是選用參數。

您可以將個別設定檔的電子郵件通知設定為設定檔通知、並將儲存庫資料庫上的多個設定檔設定為摘要通知。

*設定檔通知*

對於個別設定檔、您可以接收電子郵件、以利成功或失敗的資料庫作業。


NOTE: 根據預設、系統會針對失敗的資料庫作業啟用電子郵件通知。

*摘要通知*

「摘要通知」可讓您接收關於使用多個設定檔執行資料庫作業的摘要電子郵件。您可以啟用每小時、每日、每週或每月通知。


NOTE: 從S333.3開始SnapManager 、只有在您指定必須傳送通知的主機伺服器時、才會傳送摘要通知。如果您從SnapManager 3.3之前的版本升級支援功能、如果您尚未在摘要通知組態中指定主機伺服器、則可能不會傳送摘要通知。


NOTE: 如果您在實際應用程式叢集（RAC）環境中的某個資料庫節點上建立儲存庫、並啟用摘要通知、則稍後當您將相同的儲存庫新增至資料庫的另一個節點時、系統會傳送兩次摘要通知電子郵件。

您可以一次使用設定檔層級的通知或摘要通知。

支援下列設定檔執行資料庫作業的電子郵件通知：SnapManager

* 在主要儲存設備上建立備份
* 還原備份
* 建立複本
* 分割複本
* 驗證備份


在啟用電子郵件通知的情況下建立或更新設定檔之後、您可以將其停用。如果停用電子郵件通知、您將不再收到已執行設定檔之資料庫作業的電子郵件警示。

您收到的電子郵件包含下列詳細資料：

* 資料庫作業名稱、例如備份、還原或複製
* 用於資料庫作業的設定檔名稱
* 主機伺服器名稱
* 資料庫的系統識別碼
* 資料庫作業的開始和結束時間
* 資料庫作業狀態
* 錯誤訊息（如果有）
* 警告訊息（若有）


您可以設定下列項目：

* 儲存庫的郵件伺服器
* 新設定檔的電子郵件通知
* 現有設定檔的電子郵件通知
* 儲存庫下多個設定檔的摘要電子郵件通知



NOTE: 您可以從命令列介面（CLI）和圖形使用者介面（GUI）設定電子郵件通知。
