---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 您可以套用使用者驗證和角色型存取控制（RBAC）來管理SnapManager 功能的安全性。使用者驗證方法可讓您存取資源、例如儲存庫、主機和設定檔。RBAC可讓您限制SnapManager 針對資料庫中包含資料檔案的磁碟區和LUN執行的作業。 
---
= 安全性與認證管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以套用使用者驗證和角色型存取控制（RBAC）來管理SnapManager 功能的安全性。使用者驗證方法可讓您存取資源、例如儲存庫、主機和設定檔。RBAC可讓您限制SnapManager 針對資料庫中包含資料檔案的磁碟區和LUN執行的作業。

當您使用命令列介面（CLI）或圖形使用者介面（GUI）執行作業時SnapManager 、即可擷取儲存庫和設定檔的認證資料集。支援儲存先前安裝的認證資料。SnapManager

儲存庫和設定檔可以使用密碼加以保護。認證是為使用者設定的物件密碼、而且不會在物件本身上設定密碼。

您可以執行下列工作來管理驗證和認證：

* 透過操作時的密碼提示或使用「msap認證集」命令來管理使用者驗證。
+
設定儲存庫、主機或設定檔的認證。

* 檢視管理您有權存取之資源的認證資料。
* 清除所有資源（主機、儲存庫和設定檔）的使用者認證。
* 刪除個別資源（主機、儲存庫和設定檔）的使用者認證。


您可以執行下列工作來管理角色型存取：

* 使用SnapManager 支援功能支援RBAC for支援。SnapDrive
* 使用Operations Manager主控台將使用者指派給角色並設定角色功能。
* 或者SnapManager 、您也可以編輯「smsap.config file」來啟用支援、以儲存加密的密碼。


如果安裝了Protection Manager、存取功能會受到下列影響：

* 如果已安裝Protection Manager、則SnapManager 當您建立資料庫設定檔時、會建立一個資料集、並將包含資料庫檔案的磁碟區填入資料集。
+
完成備份作業之後SnapManager 、此功能會讓資料集內容與資料庫檔案保持同步。

* 如果未安裝Protection Manager、SnapManager 則無法建立資料集、也無法在設定檔上設定保護。

