---
permalink: unix-administration/concept-when-can-you-use-fast-restore.html 
sidebar: sidebar 
keywords: rule, apply, fast, restore, achieve, optimal, performance, guidelines 
summary: 特定規則適用於使用快速還原來達到最佳還原效能。在某些情況下、您無法使用快速還原。 
---
= 快速還原的使用準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定規則適用於使用快速還原來達到最佳還原效能。在某些情況下、您無法使用快速還原。

若要達到最佳還原效能（Volume還原或完整磁碟群組還原）、您必須遵守下列規則：

* 只有完整備份還原才符合快速還原的資格。
* 只有資料檔案才符合快速還原的資格。
* 資料檔案必須是磁碟區中唯一符合快速還原資格的檔案。
+
雖然暫用資料檔案可以存放在磁碟區中、但控制檔、記錄檔、pFiles或其他檔案必須與資料檔案位於不同的磁碟區上。您必須在獨立的磁碟區上設定Oracle資料庫、並將資料檔案與控制檔、歸檔記錄和線上記錄檔分開。

* 磁碟區中只能存在一個資料庫的資料檔案。
* 可以使用多個檔案系統、但這些檔案系統中的檔案必須是僅適用於一個資料庫的資料檔案。
* SAP需要稍微不同的檔案配置。
+
「一般配置與組態」區段包含詳細資料。

* 如果使用「BRRESTRESTORE」還原資料庫、則快速還原會搭配備份公用程式參數檔案中的FAST參數使用。



NOTE: 若要使用快速還原功能來檢查先前建立的備份是否可還原、您可以使用「msap備份還原」命令的「preview」選項。

在下列情況下、無法使用快速還原程序：

* 部分備份
* 從二線儲存設備備份時（如果主儲存設備上也存在備份）
+
您無法使用檔案型或磁碟區型還原來還原這些項目。

* 備份時使用SnapVault 不受保護
+
快速還原程序無法用於上次受保護備份之前建立的備份。不過、您可以使用快速還原程序來進行上次受保護備份之後所建立的備份。例如、考慮備份A、B和CB是最後一次使用SnapVault 支援功能將資料傳輸至二線儲存設備的備份。您可以快速還原B和C、但無法快速還原A、因為它的建立時間比上次受保護的備份還早。下列項目需要基本的支援資料才能計算時間差異、並在下次將備份傳輸至次要儲存設備時傳送至次要儲存設備。SnapVault SnapVault上次受保護的備份會做為基礎Snapshot複本。因此、使用快速還原程序可防止SnapVault 無法辨識基礎。

* 使用Snapshot複本的FlexClONE或LUN複本、這些複本是在要還原磁碟區的Snapshot複本之後建立的
+
例如、複本可能是SnapManager 由更新的備份所產生、而此備份是由NetApp掛載或複製的。

* LUN不屬於作用SnapDrive 中的「Snapshot」複本


您無法針對相同的備份執行快速還原及其他類型的還原。例如、如果一個資料磁碟區可以使用快速還原程序還原、但另一個資料磁碟區無法還原、則也無法使用快速還原程序還原。在此情況下、您可以選擇檔案型還原。

此外、您應該考量下列關於資料庫還原的要點：

* 無法還原歸檔記錄或重作記錄、但會掛載歸檔記錄檔的備份、並將其用於還原。SnapManager
* 從不使用Volume還原還原控制檔。SnapManager
* 如果您想要還原控制檔和資料檔案、SnapManager 則由下列兩個步驟執行還原。
+
還原控制檔、然後還原資料檔。SnapManager

* 如果SnapManager 在與標準表格空間檔案相同的磁碟區中找到暫用檔案、您就不需要使用置換功能來執行磁碟區層級的還原。
+
磁碟區還原之後、暫存表格空間會恢復上線。



SAP版的支援功能和BACKINT介面在判斷可以使用哪種還原機制時、都使用相同的邏輯。SnapManager無論備份是使用SnapManager SAP的版次或BACKINT介面進行、或是SnapManager 透過SAP的版次或退格介面執行還原、都可以使用所有的還原方法。

*相關資訊*

http://mysupport.netapp.com/["NetApp支援網站上的文件：mysupport.netapp.com"]
