---
permalink: unix-administration/reference-the-smosmsap-schedule-create-command.html 
sidebar: sidebar 
keywords: schedule, create, command, schedule, backup, smsap 
summary: 您可以使用排程建立命令來排程要在特定時間建立的備份。 
---
= smsap排程create命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用排程建立命令來排程要在特定時間建立的備份。



== 語法

[listing, subs="+macros"]
----
pass:quotes[smsap schedule create -profile _profile_name_
[-full{-auto | -online | -offline}
[-retain _-hourly_| _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_] [-verify]] |
pass:quotes[-data [[-files _files_ [_files_]] |
pass:quotes[-tablespaces _tablespaces_ [_tablespaces_]] {-auto | -online | -offline}
pass:quotes[[-retain _-hourly_ | -daily | _-weekly_ | _-monthly_ | _-unlimited_]] [-verify]] |
[-archivelogs]}
pass:quotes[[-label _label_]]
pass:quotes[[-comment _comment_]]
[-protect | -noprotect | -protectnow] pass:quotes[[-backup-dest _path1_ [ , _path2_]]
pass:quotes[[-exclude-dest _path1_ [ , _path2_]]] pass:quotes[[-prunelogs {-all | -until-scn _until-scn_ | -until -date  _yyyy-MM-dd:HH:mm:ss_\] | -before {-months | -days | -weeks | -hours}}
-prune-dest _prune_dest1_, [_prune_dest2_\]\]-schedule-name _schedule_name_
[-schedule-comment _schedule_comment_\] -interval {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-onetimeonly_}
-cronstring _cron_string_-start-time {_start_time < yyyy-MM-dd HH:mm_>}
-runasuser _runasuser_
[-taskspec _taskspec_]]-force
[-quiet | -verbose]
----


== 參數

* 「*設定檔_profile_name_*」
+
指定與您要排程備份之資料庫相關的設定檔名稱。設定檔包含資料庫和其他資料庫資訊的識別碼。

* *自動***選項*
+
如果資料庫處於掛載或離線狀態、SnapManager 則執行離線備份。如果資料庫處於開啟或線上狀態、SnapManager 則執行線上備份。如果您使用「-force」選項搭配「-offline」選項、SnapManager 即使資料庫目前處於線上狀態、也會強制進行離線備份。

* *線上***選項*
+
指定線上資料庫備份。

+
只要主叢集處於開啟或掛載狀態、且執行個體處於開啟狀態、您就可以建立Real Application Clusts（RAC）資料庫的線上備份。如果本機執行個體處於關機狀態、或沒有開啟執行個體、您可以使用「-force」選項進行線上備份。

+
** 如果本機執行個體處於關機狀態、且至少有一個執行個體已開啟、您可以使用-force選項將本機執行個體變更為已掛載。
** 如果沒有處於開啟狀態的執行個體、您可以使用「-force」選項將本機執行個體變更為開啟。


* *離線**選項*
+
指定資料庫處於關機狀態時的離線備份。如果資料庫處於開啟或掛載狀態、則備份會失敗。如果使用「-force」選項、SnapManager 則嘗試變更資料庫狀態、以關閉資料庫進行離線備份。

* *「*全*」*選項*
+
備份整個資料庫。這包括所有資料、歸檔記錄和控制檔。無論您執行何種類型的備份、都會備份歸檔的重作記錄和控制檔。如果您只想備份一部分資料庫、請使用「-files'」選項或「-tabl空間」選項。

* 「*檔案_list_*」
+
僅備份指定的資料檔案、加上歸檔的記錄和控制檔。以空格分隔檔案名稱清單。如果資料庫處於開啟狀態、SnapManager 則由功能驗證適當的資料表空間是否處於線上備份模式。

* 「*表格空間_表格空間_*」
+
僅備份指定的資料庫表格空間、以及歸檔的記錄和控制檔。以空格分隔表格空間名稱。如果資料庫處於開啟狀態、SnapManager 則由功能驗證適當的資料表空間是否處於線上備份模式。

* 「*標籤名稱_*」
+
指定此備份的選用名稱。此名稱在設定檔中必須是唯一的。名稱可以包含字母、數字、底線（_）和連字號（-）。它不能以連字號開頭。

+
如果您未指定標籤、SnapManager 則會以scene_type_date格式建立預設標籤：

+
** 範圍為F表示完整備份、或是P表示部分備份。
** 類型為C表示離線（冷）備份、H表示線上（熱）備份、或A表示自動備份、例如P_a_200810060037IST。
** 日期是備份的年、月、日和時間。
+
支援24小時時鐘。SnapManager



+
例如、如果您在2007年1月16日下午5：45：16離線執行資料庫完整備份東部標準時間SnapManager 、這個功能可以建立F_C_20070111111174516EST標籤。

* 「*」-「comment _stron_*」
+
指定可選的註釋來描述此備份。將字串括在單引號（'）內。

+

NOTE: 有些Shell會刪除引號。如果您的Shell確實如此、則必須使用反斜槓（\）來加上引號。例如、您可能需要輸入：「\」這是註釋。

* 「*驗證*」*選項*
+
執行Oracle DBV公用程式、確認備份中的檔案未毀損。

+

NOTE: 如果您指定「-Verify」（驗證）選項、則在驗證作業完成之前、備份作業不會完成。

* *「*力」**選項*
+
如果資料庫狀態不正確、則強制變更狀態。例如SnapManager 、根據您指定的備份類型和資料庫所在的狀態、將資料庫狀態從線上變更為離線。

+
使用線上RAC資料庫備份時、如果本機執行個體處於關機狀態、或是沒有開啟執行個體、請使用「-force」選項。

+

NOTE: Oracle版本必須為10.2.0.5；否則、如果RAC中有任何執行個體已掛載、資料庫將會掛起。

+
** 如果本機執行個體處於關機狀態、且至少有一個執行個體已開啟、您可以使用「-force」選項將本機執行個體變更為已掛載。
** 如果沒有開啟執行個體、您可以使用「-force」選項將本機執行個體變更為開啟。


* 「*保護」|「-nosprotProtect」|「-protectnow*」
+
指出備份是否應受到二線儲存設備的保護。nosprote"選項指定不應將備份保護到二線儲存設備。只有完整備份受到保護。如果未指定任何選項、SnapManager 則當備份是完整備份、且設定檔指定保護原則時、預設會使用支援功能來保護備份。「-protectNOW」選項僅適用於Data ONTAP 以7-Mode運作的VMware。此選項會指定將備份立即保護至次要儲存設備。

* 「*」-「保留」｛-每小時|-每日|-每週|-每月|-無限量｝*
+
指定備份應以每小時、每日、每週、每月或無限的方式保留。如果未指定"-retif省"選項、則保留類別預設為"-Hour"。若要永久保留備份、請使用「無限」選項。「無限」選項可讓備份不符合保留原則刪除的資格。

* 《*歸檔者*》
+
指定建立歸檔記錄備份。

* 「*備份目的地_path1」、「、」、「_（路徑2）_」*
+
指定歸檔記錄備份的歸檔記錄目的地。

* "*—exclude目的地_path1_、[、_[path2]_]*
+
指定要從備份中排除的歸檔記錄目的地。

* 「*」-「*」-「*」-「全部」|「直到」-「scnate-scn」|「直到資料日期」-「月-日」-「-週」|「-小時」｝「*」之前
+
根據建立備份時所提供的選項、指定是否從歸檔記錄目的地刪除歸檔記錄檔。「-all」選項會從歸檔記錄目的地刪除所有歸檔記錄檔檔案。在指定的系統變更編號（SCN）之前、「直到SCN」選項會刪除歸檔記錄檔。「直到日期」選項會刪除歸檔記錄檔、直到指定的時間段為止。「之前」選項會在指定的時間段（天、月、週、小時）之前刪除歸檔記錄檔。

* 「*排程名稱_排程名稱_*」
+
指定您為排程提供的名稱。

* 「*」-「排程」-「留言」_schedule_comment」*
+
指定可選的註釋來說明如何排程備份。

* 「*間隔｛-每小時|-每日|-每週|-每月|-僅限一次時間｝*」
+
指定建立備份的時間間隔。您可以排程每小時、每日、每週、每月或僅一次的備份。

* -cronstring_cron_string_*
+
指定使用cronstring排程備份。cron運算式用於設定CronTrigger的執行個體。cron運算式是由下列子運算式所組成的字串：

+
** 1指秒。
** 2指分鐘。
** 3指小時。
** 4指一個月內的一天。
** 5指的是月份。
** 6指一週中的一天。
** 7指的是年份（選用）。


* 「*開始時間_西元年-月-日、日：月_日*」
+
指定排程作業的開始時間。排程開始時間應包含在西元年-月-日、日：公釐格式中。

* 執行中使用者_Runasuser_*
+
指定在排程備份時變更排程備份作業的使用者（root使用者或Oracle使用者）。

* 「*」taskspec_taskspec_*
+
指定可用於備份作業的預先處理活動或後處理活動的工作規格XML檔案。XML檔案的完整路徑必須隨附「taskspec」選項。

* 「*無聲*」
+
僅在主控台顯示錯誤訊息。預設為顯示錯誤和警告訊息。

* 「*」-「Verbos*」
+
在主控台顯示錯誤、警告和資訊訊息。


