---
permalink: unix-administration/task-configure-e-mail-notification-for-a-new-profile.html 
sidebar: sidebar 
keywords: creating, create, configure, configuring, email, notification, profile, database, operation 
summary: 建立新設定檔時、您可以設定在資料庫作業完成時接收電子郵件通知。 
---
= 設定新設定檔的電子郵件通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立新設定檔時、您可以設定在資料庫作業完成時接收電子郵件通知。

*您需要的是什麼*

* 您必須設定傳送警示的電子郵件地址。
* 您必須針對多個電子郵件地址使用以逗號分隔的清單。
+
您必須確保在逗號和下一個電子郵件地址之間沒有空格。



.步驟
. 輸入下列命令：
+
_smsap設定檔create -profile _profile_[-profile-password _profile_password_]-reposite-dbname _repo_service_name_-host _repo_host_-port _repo_port_-log-username_-database-dbname _dbdbname_-host _dhourly _stock_[-sdb_dim小時 內登入密碼_stock_stock_][_sid_stock_stock_enued_deed_de_deed_deed_deed_deed_sta_tms_[-s_-pd_stock_stock_stock_enyour_en_deed_deed_deed_deed_deed_deed_deed_deed_deed_deed_deed_deed_[-s_-s__staed_sta_ts__staed_staed_stock_stock_ [-count_n_][-dim_m_][-flex每 週[-count_n_][-dim_m_][-mon月刊[-count_n_][-duration _m_]][-comment _comment _][-snapname-Pattern_][-protection [-policy_policy_name_]電子郵件主題電子郵件通知單電子郵件主題1、主題電子郵件、主題電子郵件、主題2、電子郵件、主題電子郵件、主題2、電子郵件、電子郵件、主題電子郵件、主題2、電子郵件、電子郵件、電子郵件、主題2、電子郵件

+
此命令的其他選項如下：

+
《暴力》

+
「-quiet |-verbose]」

+

NOTE: 支援最多1000個字元的電子郵件地址。SnapManager

+
當您使用設定檔（建立個別的歸檔記錄備份）一起建立資料檔案和歸檔記錄檔備份、而且資料檔案備份建立失敗時、電子郵件通知會以作業名稱的形式傳送資料備份、而非以資料備份和歸檔記錄備份的形式傳送。當資料檔案和歸檔記錄檔備份作業成功時、您會看到下列輸出：

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----


'''
下列範例顯示建立新設定檔時所設定的電子郵件通知：

[listing]
----

smsap profile create -profile sales1 -profile-password sales1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username oba5 -database -dbname DB1 -host 10.72.197.142 -sid DB1 -osaccount oracle
-osgroup dba -notification -success -email admin1@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----
'''