---
permalink: unix-administration/task-perform-backup-restore-and-clone-operations-using-prescript-and-post-scripts.html 
sidebar: sidebar 
keywords: script, initiate, initiating, backup, restore, clone, operation, snapmanager, display, task-enabling, create, wizard, restore, recover, parameter, post-script 
summary: 您可以在開始備份、還原或複製作業時、使用自己的指令碼。在「備份建立精靈」、「還原或還原精靈」或「Clone Create精靈」中顯示「工作啟用」頁面、您可以在其中選取指令碼、並為指令碼所需的任何參數提供值。SnapManager 
---
= 使用指令碼和指令碼後執行備份、還原和複製作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在開始備份、還原或複製作業時、使用自己的指令碼。在「備份建立精靈」、「還原或還原精靈」或「Clone Create精靈」中顯示「工作啟用」頁面、您可以在其中選取指令碼、並為指令碼所需的任何參數提供值。SnapManager

*您需要的是什麼*

* 將外掛程式指令碼安裝在正確SnapManager 的安裝位置。
* 使用命令確認外掛程式安裝正確。
* 請確定您使用的是Bash Shell。


*關於此工作*

在命令列介面（CLI）中、列出指令碼名稱、選取參數、然後設定值。

.步驟
. 若要驗證您是否正在使用Bash Shell、請在命令提示字元中輸入下列命令：
+
《* Basash*》

+
或者、您也可以在提示字元輸入「bash」命令、然後使用命令輸出做為指令碼的開始參數。

+
如果沒有看到錯誤、則表示Bash Shell運作正常。

. 對於備份作業、請輸入「taskspec」選項、並提供工作規格XML檔案的絕對路徑、以便在備份作業之前或之後執行預先處理或後處理活動：
+
「* smsap備份建立設定檔_profile_name_｛[-full｛-online |-offline |-auto｝[-sthourly |[-dayly |-fleyly |-mourly |-monthly |-monthly |-unchallyly |-scap空間__[-stourly databar空間]|[-hourly ]每月一次、每週一次、每週一次、每週一次、每週一次、每次、每次、每個月一次、每次、_、每次、每次、每次、每次、每次、每次、每次、每次不限 [-archivelogs [-label _][-comment _comment _][-protect_-protection |-protectnow][-backup-dest_path1_[,[_path2_][-exclude taskogs {-all |-untiluntuniluned*前的備份數分鐘__dest_mintask_mindest_mind [-ed_mindest_mindest_mind前的備份數][_mintasked_mindest_ed'[-mindest_mindest_ed'[-ed'[-mindest_ed'[-ed_ed_ed_dest_dest_date ][-ed_ed_ed_edtaskedtasked_detrivest_][-ed__小時][-ths [-stycloprs[-min][-thised_min][

+
如果備份外掛程式作業失敗、則只會顯示外掛程式名稱和傳回代碼。外掛程式指令碼必須包含記錄訊息、並將訊息重新導向至使用者定義的記錄檔。

. 對於備份還原作業、請輸入「taskspec」選項、並提供工作規格XML檔案的絕對路徑、以便在還原作業之前或之後執行預先處理或後處理活動：
+
hy*smsap備份還原-profile _profile_name_｛-label __|-id _<id>_｝｛-files__|-tabl空間__|-solet空間__|-fone |-controlfiles｝[-recoverestate {_-alllogs_|_nosap備份還原備份還原備份還原-detoid__<-tunest____<enature>___________oestampallyoid>[-id_][-restoreat restoreed'[-restoreed'[-restore[-stamptasked][-id_stamptask_][-id_][-restoreed'[-restoreed] taskec[-stamptask_][-restore[

+
如果還原外掛程式作業失敗、則只會顯示外掛程式名稱和傳回代碼。外掛程式指令碼必須包含記錄訊息、並將訊息重新導向至使用者定義的記錄檔。

. 對於實體複本建立作業、請輸入-taskspec選項、並提供工作規格XML檔案的絕對路徑、以便在實體複本作業之前或之後執行預先處理或後處理活動：
+
hy*smsap clone create -profile _profile_name_{-backup-label _backup_name_|-backup-id _|-current}-newsid _new_sid_-clonespec _fact_to_clonespecfile_[-Reserve _<是、否、繼承>_][主機<備份標籤_ verbose task_<備份_<備份ID <備份_<備份_備份_備份_<備份_備份_備份_備份_備份_<備份_<備份_資訊_<備份_<備份_資訊><備份_備份_<資訊><資訊><資訊><資訊><資訊><資訊><資訊><

+
如果複製外掛程式作業失敗、則只會顯示外掛程式名稱和傳回代碼。外掛程式指令碼必須包含記錄訊息、並將訊息重新導向至使用者定義的記錄檔。



'''


== 使用工作規格XML檔案建立備份的範例

[listing]
----
smsap backup create -profile SALES1 -full -online -taskspec sales1_taskspec.xml -force -verify
----
'''