---
permalink: unix-administration/task-update-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, database, operating, system, os, authentication, updating, information, host, database, oracle, updating 
summary: 您可以更新設定檔以修改設定檔密碼、保留的備份數目、資料庫存取權、資料庫驗證的作業系統（OS）驗證、以及主機的相關資訊。如果Oracle資料庫密碼資訊變更、您也必須在設定檔中變更該資訊。 
---
= 更新設定檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更新設定檔以修改設定檔密碼、保留的備份數目、資料庫存取權、資料庫驗證的作業系統（OS）驗證、以及主機的相關資訊。如果Oracle資料庫密碼資訊變更、您也必須在設定檔中變更該資訊。

*關於此工作*

如果設定檔已啟用保護原則、您就無法使用SnapManager 效益分析來變更原則。儲存管理員必須使用Protection Manager的主控台來變更原則。

使用「分隔-歸檔儲存記錄備份」選項、即可更新設定檔（3.2或更新版本）、將歸檔記錄備份與資料檔案備份分開。SnapManager您可以為歸檔記錄備份指定個別的保留期間和保護原則。利用NetApp技術、您可以將歸檔記錄備份與線上資料庫備份一起納入其中。SnapManager您也可以一起建立線上資料檔案備份與歸檔記錄備份、以便進行複製。建立線上資料檔案備份時、會立即建立歸檔記錄備份及資料檔案。

.步驟
. 輸入下列命令：
+
_smsap profile update -profile _profile_[-new-profile _new_profile_name_][-profile-password _profile_password_][-database-dbname _dbname_-host _db_host_[-sid_db_sid_][-login-username_db_username_-password__dhour_station___station___station_msn___station__station___msn___station__[_station_station_station_station_ms______-am__station__密碼分號文件[_station_] [每週[-count_n_][-dimation _m_][-m_][月數[-count_n_][月數_m_]][評論_comment _][-addresssnapname -Pattern_][-protection [-protection [-policy _policy_name_]|[-protection mise_edays備份資料不限電子郵件][月數_、電子郵件、電子郵件主題備份數_、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、主題備份數][_、電子郵件、電子郵件、主題備份數_、主題備份數_、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、主題備份數[_、主題備份數_、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、電子郵件、共數_、共數_、共數_、共2天_、共2天_、共2天

+
此命令的其他選項如下：

+
「-force」[-noprompel]

+
「-quiet | verbose]」

+
[cols="2a,4a"]
|===
| 如果您想要... | 然後... 


 a| 
*變更設定檔以使用作業系統驗證*
 a| 
請指定下列項目、而非新增使用者名稱、密碼和連接埠：

** 作業系統帳戶的名稱為-osAccount _account_name_'
** -osgroup _osgroup是與作業系統帳戶相關聯的群組、通常是用來安裝Oracle的帳戶




 a| 
*使用自動儲存管理（ASM）執行個體驗證來建立設定檔*
 a| 
指定ASM執行個體驗證的認證資料。

** 「-asmusername _asminstation_username_」是用來登入ASM執行個體的使用者名稱。
** asmpassword _asminstance_password_是用於登入ASM執行個體的密碼。




 a| 
*使用目錄作為Oracle Recovery Manager（RMAN）儲存庫、或是您要移除RMAN *
 a| 
指定下列選項和變數：

** tnssnames.ora檔案中定義的tnssname。
** 以「-login-username_usernam__」作為連線至RMAN目錄所需的使用者名稱。
+
如果未指定、SnapManager 則使用作業系統驗證資訊。您無法將作業系統驗證用於實際應用程式叢集（RAC）資料庫。

** 密碼_password_'是連線至RMAN目錄所需的RMAN密碼。
** 如果您使用控制檔做為RMAN儲存庫、則為controlfile'。
** 移除RMAN。




 a| 
*變更設定檔中資料庫備份的備份保留原則*
 a| 
指定保留類別的保留計數或保留持續時間、或同時指定兩者以變更保留原則。持續時間以課程單位為單位（例如小時、日）。

** 「每小時」是指每小時的保留類別、其中「[-count_n_][-duration _m_]」分別是保留數和保留期間。
** 「每日」是每日保留類別、其「記錄編號_n_][-duration _m_]」分別是保留數和保留時間。
** 「每週」是每週保留類別、而「-count_n_][-duration _m_]」則分別是保留數和保留期間。
** 「每月」是每月保留類別、其「記錄次數_n_]（-持續時間_m_]）」分別為保留數和保留期間。




 a| 
*停用設定檔的備份保護*
 a| 
指定「nosProtect」以不保護使用設定檔所建立的資料庫備份。如果設定檔已啟用「-Protect」、如果您想停用Protect、會顯示一則警告訊息、指出此動作將刪除資料集、而且您將無法還原或複製此設定檔的備份。



 a| 
*啟用資料庫作業完成狀態的電子郵件通知*
 a| 
指定下列選項和變數：

** 「摘要通知」可讓您針對儲存庫資料庫下的多個設定檔設定摘要電子郵件通知。
** 「通知」可讓您接收設定檔資料庫作業完成狀態的電子郵件通知。
** 「-'成功-電子郵件_email_address2_」可讓您在使用新的或現有的設定檔成功執行資料庫作業之後、收到電子郵件通知。
** 「-fam失敗-email_email_address2_」可讓您接收電子郵件通知、通知您使用新的或現有的設定檔執行失敗的資料庫作業。
** 主題_Subject _text_'指定建立新設定檔或現有設定檔時、電子郵件通知的主旨文字。如果通知設定未針對儲存庫進行設定、而您嘗試使用命令列介面（CLI）設定設定設定檔或摘要通知、則主控台記錄中會記錄下列訊息：「SAP-1477: Notification Settings Not Configure（通知設定未設定）」。
+
如果您已設定通知設定、且嘗試使用CLI設定摘要通知、但未啟用儲存庫的摘要通知、則主控台記錄中會記錄下列訊息：「MSAP-14775：摘要通知組態無法用於此儲存庫」





 a| 
*更新設定檔以分別建立歸檔記錄檔的備份*
 a| 
指定下列選項和變數：

** 您可以使用「分隔的archivelog-Backup」來建立與資料庫檔案分開的歸檔記錄檔備份。
+
指定此選項之後、您可以建立純資料檔案備份或僅歸檔程式備份。您無法建立完整備份。此外、您也無法透過分隔備份來還原設定檔設定。根據保留原則、還原在進行僅歸檔程式備份之前所建立的備份。SnapManager

** 「-ret-archivelog-Backups」可設定歸檔記錄備份的保留時間。
+

NOTE: 如果您是第一次更新設定檔、可以使用「分隔的歸檔記錄備份」選項、將歸檔記錄備份與資料檔案備份區隔開；您必須使用「-retave-archivelog-backups」選項來提供歸檔記錄備份的保留時間。稍後更新設定檔時、您可選擇是否要設定保留期間。

** 「-Protect」會在Data Fabric Manager（DFM）伺服器中建立應用程式資料集、並新增與資料庫、資料檔案、控制檔及歸檔記錄相關的成員。
+
如果資料集存在、則會在建立設定檔時重複使用。

** 保護原則將保護原則設定為歸檔記錄備份。
** 「包括線上備份」是指將歸檔記錄備份與資料庫備份一起納入。
** 「不含線上備份」指定資料庫備份不包含歸檔記錄檔檔案備份。




 a| 
*變更目標資料庫的主機名稱*
 a| 
指定「-host _new_db_host_」來變更設定檔的主機名稱。



 a| 
*在設定檔更新作業之後收集傾印檔*
 a| 
指定"-dump（轉儲）"選項。

|===
. 若要檢視更新的設定檔、請輸入下列命令：「msap profile show」

