---
permalink: unix-administration/task-use-protection-manager-to-configure-secondary-backup-schedules.html 
sidebar: sidebar 
keywords: support, backup, database, secondary, storage, administrator, protection, manager, configure, schedule 
summary: 為了支援將資料庫備份至二線儲存設備、儲存管理員使用Protection Manager來設定備份排程。 
---
= 使用Protection Manager來設定次要備份排程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了支援將資料庫備份至二線儲存設備、儲存管理員使用Protection Manager來設定備份排程。

*您需要的是什麼*

在設定次要備份排程之前、儲存管理員會向DBA合作夥伴授予下列資訊：

* DBA希望次要備份遵循的排程。
+
在這種情況下、每日一次的備份會在下午7點進行每週一次的備份時間是星期六上午1點



.步驟
. 前往Protection Manager的NetApp管理主控台。
. 在功能表列中、按一下*原則*>*保護*>*排程*。
+
隨即顯示Protection Policies（保護原則）視窗的「排程」（排程）索引標籤。

. 在排程清單中選取每日排程（每天晚上8：00）*。
. 按一下 * 複本 * 。
+
新的每日排程*複本為每天晚上8：00 *、會顯示在清單中。已選取。

. 按一下 * 編輯 * 。
+
「編輯每日排程」內容表隨即開啟、顯示「排程」索引標籤。

. 將排程名稱變更為*每日下午7點薪資*、更新說明、然後按一下*套用*。
+
您的變更隨即儲存。

. 按一下「*每日事件*」索引標籤。
+
排程目前的每日備份時間為下午8：00即會顯示。

. 按一下「*新增*」並在新的時間欄位中輸入* 7：00 PM*、然後按一下「*套用*」。
+
排程目前的每日備份時間為下午7：00

. 按一下「*確定*」以儲存變更並結束屬性表。
+
您的新每日排程*每日薪資於下午7點*會顯示在排程清單中。

. 在排程清單中選取每週排程*星期日下午8：00加上每日*。
. 按一下 * 複本 * 。
+
新的每週排程（*週日複本、下午8：00加上每日*）會顯示在清單中。已選取。

. 按一下 * 編輯 * 。
+
「編輯每週排程」內容表隨即開啟、顯示「排程」索引標籤。

. 將排程名稱變更為* Payroll星期六、上午1點加上每日下午7點*、然後更新說明。
. 從「*每日排程*」下拉式清單中、選取您剛建立的每日排程、*每天下午7點的薪資*。
+
選擇*每日薪資於下午7點*表示此排程會定義當*每日薪資週六的上午1點加上每日的下午7點*排程套用至原則時、每日作業的發生時間。

. 按一下「*確定*」以儲存變更並結束屬性表。
+
您的新每週排程（*薪資週六上午1點加上每日下午7點*）會顯示在排程清單中。


