---
permalink: unix-administration/task-update-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, ability, update, host, name, target, database, profile 
summary: SAP適用的BIOS（3.2或更新版本）可在BIOS設定檔中更新目標資料庫的主機名稱。SnapManager SnapManager 
---
= 更新與設定檔相關聯的目標資料庫主機名稱
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP適用的BIOS（3.2或更新版本）可在BIOS設定檔中更新目標資料庫的主機名稱。SnapManager SnapManager

*您需要的是什麼*

* 本機使用者的主目錄必須知道設定檔對儲存庫的對應。
* 必須關閉圖形化使用者介面（GUI）工作階段。SnapManager
* 在真實應用程式叢集（RAC）環境中、必須刪除及卸載設定檔中指定主機上可用的複本或掛載備份。


*關於此工作*

您只能使用CLI、以新的主機名稱更新設定檔。

*不支援在設定檔*中變更目標資料庫主機名稱的情況

下列情況不支援變更設定檔中的目標資料庫主機名稱：

* 使用SnapManager Isname GUI變更目標資料庫主機名稱
* 更新設定檔的目標資料庫主機名稱後、將儲存庫資料庫復原
* 執行單一命令來更新新目標資料庫主機名稱的多個設定檔
* 執行SnapManager 任何功能不全的作業時、請變更目標資料庫主機名稱
* 如果SnapManager 在Solaris上安裝了支援程序、而且資料庫邏輯單元編號（LUN）是使用裝有SVM堆疊的主機掛載檔案系統來建立、請變更目標資料庫主機名稱。



NOTE: 在設定檔中更新目標資料庫主機名稱之後、只會變更目標資料庫主機名稱。設定檔上設定的所有其他組態參數都會保留。

在啟用保護的設定檔中更新新的目標資料庫主機名稱之後、更新的設定檔會保留相同的資料集和保護原則。

變更目標主機的主機名稱之後、您必須確保在建立新的受保護設定檔之前、先更新所有現有受保護設定檔的主機名稱。若要更新設定檔的主機名稱、請執行「msap profile update」命令。

更新目標資料庫主機名稱之後、如果新主機中沒有可用的實體複本或掛載備份、則無法刪除或分割實體複本或卸載備份。在這種情況SnapManager 下、從新主機執行支援功能會導致故障、以及舊主機中的過時項目。若要執行SnapManager 還原作業、您必須使用「profile update」（設定檔更新）來還原至先前的主機名稱。

. 輸入下列命令：
+
_smsap profile update -profile _profile_[-profile-password _profile_password_][-database-dbname _dbname_-host _db_host_[-sID db_sid_][-log-userName _db_username_-password _db_password_-port _db_port_][{-rmne-lam_dourly controllam_en_de_按月_[_n_n次按小時發送_次輸入密碼_次_次_次_次_次輸入_次_次_次_次輸入_次輸入_次_次_次_次_次_次_次_次_次_次_次_次_次_次輸入_次輸入_次_次_次_次輸入_次輸入_次輸入_次輸入_次_次_次_次輸入_次_次_次_次_次_次輸入_次_次_次密碼_次_次_次_次_次_次_次_次輸入_次輸入_次_ [-dump dim_]][-comment _comment _][-snapname-Pattern_][-protection [-protection -policy _policy_name_]|[-noprotection ][-note-noticle_noticle_noteed][-notification（電子郵件_電子郵件_電子郵件_地址1、電子郵件地址2 _地址_、主題備份數_、主題_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、主題備份數_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件地址_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件地址_、電子郵件_、主題備份數_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件_、電子郵件地址_、電子郵件_、電子郵件_、電子郵件_、電子郵件_

+
此命令的其他選項如下：

+
「-force」[-noprompel]

+
「-quiet |-verbose]」

+
[cols="1a,2a"]
|===
| 如果您想要... | 然後... 


 a| 
*變更目標資料庫主機名稱*
 a| 
'指定主機_new_db_host_'

|===
. 若要檢視設定檔的目標資料庫主機名稱、請輸入下列命令：
+
「* smsap profile show*」


