---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr
sidebar:
  entries:
  - title: 適用於SAP文件的SnapManager
    url: "/index.html"
  - title: 版本資訊
    url: "/reference-releasenotes.html"
  - section: unix-installation-cmode
  - section: unix-installation-7mode
  - section: unix-administration
  - section: windows
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 產品總覽
      url: "/unix-installation-cmode/reference-smsap-isg-product-overview.html"
    - title: 版本資訊
      url: reference-releasenotes.html
  - title: 系統管理
    links:
    - title: 設定SnapManager 適用於UNIX的功能
      url: "/unix-administration/concept-configuring-snapmanager-for-oraclesap.html"
    - title: 設定SnapManager 適用於Windows的功能
      url: "/windows/concept-configuring-snapmanager-for-oraclesap.html"
  - title: 安裝與設定
    links:
    - title: 部署工作流程（7-Mode）
      url: "/unix-installation-7mode/reference-smsap-isg-deployment-workflow.html"
    - title: 部署工作流程（叢集模式）
      url: "/unix-installation-cmode/reference-smsap-isg-deployment-workflow.html"
  - title: 更多資源
    links:
    - title: NetApp支援
      url: https://mysupport.netapp.com/site/global/dashboard
    - title: NetApp社群
      url: https://community.netapp.com/
