---
permalink: unix-installation-cmode/task-upgrade-snapmanager-for-oracle-snapmanager-for-sap-hosts.html 
sidebar: sidebar 
keywords: upgrade, exist, host, version, snapmanager, simultaneous, result, downtime 
summary: 您可以升級所有現有主機、以使用SnapManager 最新版的功能。所有主機都會同時升級。不過、這可能會導致所有SnapManager 的故障主機停機、並在這段時間內排定營運。 
---
= 升級SnapManager 功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級所有現有主機、以使用SnapManager 最新版的功能。所有主機都會同時升級。不過、這可能會導致所有SnapManager 的故障主機停機、並在這段時間內排定營運。

.步驟
. 以root使用者身分登入主機系統。
. 從命令列介面（CLI）、瀏覽至您下載安裝檔案的位置。
. 選用：如果檔案不可執行、請變更權限：「chmod544 netapp.smsap*」
. 停止SnapManager 該伺服器：「msap_server stop」
. 視UNIX主機而定、安裝SnapManager 下列項目：
+
|===
| 如果作業系統是... | 然後執行... 


 a| 
* Solaris（SPARC）*
 a| 
？？/NetApp .smsap.Sunos-SPARC®版本_number.bin



 a| 
* Solaris（x86_64）*
 a| 
/.NetApp.smsap.Sunos-x64-version_number.bin



 a| 
* AIX（PPC64）*
 a| 
/NetApp .smsap.AIX-ppc64-version_number.bin



 a| 
* Linux x86_64
 a| 
/NetApp .smsap.Linux - x86版_number.bin



 a| 
* Linux x64*
 a| 
/NetApp .smsap.Linux - x64-version_number.bin

|===
. 在* Introduction *（簡介*）頁面上、按* Enter *繼續。
+
畫面會顯示以下訊息：「Exexisting SnapManager sfor SAP detected.」（已偵測到SAP的現有功能）

. 按* Enter *。
. 在命令提示字元中、執行下列步驟：
+
.. 將作業系統使用者的預設值變更為* ora*`_sid_'。
+
「_SID_」是SAP資料庫的系統識別碼。

.. 輸入作業系統群組的正確值、或按* Enter *接受預設值。
.. 輸入伺服器啟動類型的正確值、或按* Enter *接受預設值。


+
隨即顯示組態摘要。

. 按* Enter鍵*繼續。
+
畫面會顯示下列訊息：「解除安裝現有SnapManager 的SAP用功能已開始」。

+
完成解除安裝、SnapManager 並安裝最新版的更新版本的功能。


