---
permalink: unix-installation-cmode/task-smsap-isg-create-a-profile-for-your-database.html 
sidebar: sidebar 
keywords: create, profile, database, perform, operation, contain, information, reference, multiple 
summary: 您必須為資料庫建立設定檔、才能在該資料庫上執行任何作業。設定檔包含資料庫的相關資訊、只能參考一個資料庫；不過、資料庫可以由多個設定檔參考。使用一個設定檔建立的備份無法從不同的設定檔存取、即使兩個設定檔都與相同的資料庫相關聯。 
---
= 建立資料庫的設定檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須為資料庫建立設定檔、才能在該資料庫上執行任何作業。設定檔包含資料庫的相關資訊、只能參考一個資料庫；不過、資料庫可以由多個設定檔參考。使用一個設定檔建立的備份無法從不同的設定檔存取、即使兩個設定檔都與相同的資料庫相關聯。



== 您需要的產品

您必須確保目標資料庫詳細資料包含在「/etc/oratab」檔案中。



== 關於這項工作

這些步驟說明如何使用SnapManager UI為資料庫建立設定檔。您也可以視需要使用CLI。

如需如何使用CLI建立設定檔的相關資訊、請參閱SnapManager UNIX適用的_適用於SAP管理指南。

.步驟
. 在儲存庫樹狀結構中、以滑鼠右鍵按一下儲存庫或主機、然後選取*「Create Profile*（建立設定檔*）」。
. 在「*設定檔組態資訊*」頁面上、輸入設定檔的自訂名稱和密碼。
. 在「*資料庫組態資訊*」頁面上、輸入下列資訊：
+
|===
| 在此欄位中... | 執行此動作... 


 a| 
*資料庫名稱*
 a| 
輸入您要備份的資料庫名稱。



 a| 
*資料庫SID*
 a| 
輸入資料庫的安全ID（SID）。資料庫名稱和資料庫SID可以相同。



 a| 
*主機*
 a| 
輸入目標資料庫所在主機的IP位址。如果在網域名稱系統（DNS）中指定主機名稱、也可以指定主機名稱。



 a| 
*主機帳戶*
 a| 
輸入目標資料庫的Oracle使用者名稱。使用者的預設值為Oracle。



 a| 
*主機群組*
 a| 
輸入Oracle使用者群組名稱。預設值為dba。

|===
. 在「*資料庫連線資訊*」頁面上、選取下列其中一項：
+
|===
| 請選擇此選項... | 如果您想要... 


 a| 
*使用O/S驗證*
 a| 
使用作業系統維護的認證資料來驗證存取資料庫的使用者。



 a| 
*使用資料庫驗證*
 a| 
允許Oracle使用密碼檔案驗證來驗證管理使用者。輸入適當的資料庫連線資訊。

** 在「* SYSDBA優先使用者名稱*」欄位中、輸入具有管理權限的資料庫管理員名稱。
** 在*密碼*欄位中、輸入資料庫管理員的密碼。
** 在「*連接埠*」欄位中、輸入用來連線至資料庫所在主機的連接埠號碼。
+
預設值為1527。





 a| 
*使用ASM執行個體驗證*
 a| 
允許自動儲存管理（ASM）資料庫執行個體驗證管理使用者。輸入適當的ASM執行個體驗證資訊。

** 在「* SysIBA/SysSASM優先使用者名稱*」欄位中、輸入具有管理權限的ASM執行個體管理員使用者名稱。
** 在*密碼*欄位中、輸入系統管理員的密碼。


|===
+
[NOTE]
====
只有在資料庫主機上有ASM執行個體時、才能選取ASM驗證模式。

====
. 在「* RMAN組態資訊*」頁面上、選取下列其中一項：
+
|===
| 請選擇此選項... | 如果... 


 a| 
*請勿使用RMAN *
 a| 
您並未使用RMAN來管理備份與還原作業。



 a| 
*透過控制檔使用RMAN *
 a| 
您正在使用控制檔來管理RMAN儲存庫。



 a| 
*透過「恢復目錄」使用RMAN *
 a| 
您正在使用恢復目錄資料庫來管理RMAN儲存庫。輸入有權存取恢復目錄資料庫、密碼的使用者名稱、以及管理透明網路基底（TNS）連線之資料庫的Oracle net服務名稱。

|===
. 在「* Snapshot Naming Information *」（* Snapshot命名資訊*）頁面上、選取變數以指定Snapshot複本的命名格式。
+
您必須在命名格式中包含SMID變數。_SMID_變數會建立唯一的Snapshot識別碼。

. 在「*原則設定*」頁面上、執行下列步驟：
+
.. 輸入每個保留類別的保留計數和持續時間。
.. 從*保護原則*下拉式清單中、選取保護原則。
+
您必須選擇_SnapManager®cDOT_Mirror_或_SnapManager®cDOT_Vault_原則、取決SnapVault 於SnapMirror或是建立的不相關性。

.. 如果您要個別備份歸檔記錄、請選取「*備份歸檔資料個別*」核取方塊、指定保留資料、然後選取保護原則。
+
您可以選取不同於資料檔案相關原則的原則。例如、如果您已針對資料檔案選取_SnapManager®cDOT_Mirror_、則可以選取_SnapManager®cDOT_Vault_作為歸檔記錄。



. 在「*設定通知設定*」頁面上、指定電子郵件通知設定。
. 在「*歷史組態資訊*」頁面上、選取其中一個選項來維護SnapManager 關於這個操作的歷史記錄。
. 在「*執行設定檔建立作業*」頁面上、確認資訊、然後按一下「*建立*」。
. 按一下「*完成*」以關閉精靈。
+
如果作業失敗、請按一下*作業詳細資料*以檢視導致作業失敗的原因。



*相關資訊*

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["適用於UNIX的SAP系統管理指南SnapManager"^]
