---
permalink: unix-installation-7mode/concept-smsap-isg-defining-a-backup-strategy.html 
sidebar: sidebar 
keywords: define, defining, backup, strategy, creating, create, ensure, service, level, agreement, sla 
summary: 在建立備份之前定義備份策略、可確保您擁有備份、以順利還原資料庫。提供彈性的精細備份排程、以符合您的服務層級協議（SLA）SnapManager 。 
---
= 定義備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立備份之前定義備份策略、可確保您擁有備份、以順利還原資料庫。提供彈性的精細備份排程、以符合您的服務層級協議（SLA）SnapManager 。


NOTE: 如需SnapManager 最佳實務做法、請參閱_TR 3761_。



== 您需要哪種SnapManager 模式的支援才能進行支援？

支援兩種備份模式：SnapManager

[cols="1a,3a"]
|===
| 備份模式 | 說明 


 a| 
線上備份
 a| 
當資料庫處於線上狀態時、建立資料庫的備份。此備份模式也稱為熱備份。



 a| 
離線備份
 a| 
當資料庫處於掛載或關機狀態時、建立資料庫的備份。此備份模式也稱為冷備份。

|===


== 您需要哪種SnapManager 類型的支援呢？

支援三種備份類型：SnapManager

[cols="1a,3a"]
|===
| 備份類型 | 說明 


 a| 
完整備份
 a| 
建立整個資料庫的備份、其中包含所有資料檔案、控制檔和歸檔記錄檔。



 a| 
部分備份
 a| 
建立所選資料檔案、控制檔、表格空間和歸檔記錄檔的備份



 a| 
僅歸檔記錄備份
 a| 
僅建立歸檔記錄檔的備份。您必須在建立設定檔時、選取*備份歸檔資料個別*。

|===


== 您需要哪種類型的資料庫設定檔？

根據資料庫設定檔是否將歸檔記錄備份與資料檔案備份分開、而建立備份。SnapManager

[cols="2a,3a"]
|===
| 設定檔類型 | 說明 


 a| 
單一資料庫設定檔、可合併備份資料檔案和歸檔記錄
 a| 
可讓您建立：

* 完整備份包含所有資料檔案、歸檔記錄檔及控制檔
* 部分備份包含選取的資料檔案、表格空間、歸檔記錄檔及控制檔




 a| 
用於歸檔記錄備份和資料檔案備份的個別資料庫設定檔
 a| 
可讓您建立：

* 將備份與不同的標籤結合使用、以進行資料檔案備份和歸檔記錄備份
* 純資料檔案-所有資料檔案及控制檔的備份
* 部分純資料檔案備份：選取的資料檔案或表格空間以及控制檔
* 僅歸檔記錄備份


|===


== Snapshot複本應使用哪些命名慣例？

備份所建立的Snapshot複本可以遵循自訂命名慣例。您SnapManager 可以使用自訂文字或內建變數、例如設定檔名稱、資料庫名稱、以及由支援中心提供的資料庫SID、來建立命名慣例。您可以在建立原則時建立命名慣例。


NOTE: 您必須在命名格式中包含SMID變數。SMID變數會建立唯一的Snapshot識別碼。

Snapshot複本命名慣例可在建立設定檔期間或之後變更。更新的模式僅適用於尚未建立的Snapshot複本；現有的Snapshot複本則保留先前的模式。



== 您想要在主要儲存系統和次要儲存系統上保留備份複本多久？

備份保留原則會指定要保留的成功備份數目。您可以在建立原則時指定保留原則。

您可以選取「每小時」、「每日」、「每週」、「每月」或「無限」作為保留類別。對於每個保留類別、您可以一起或個別指定保留計數和保留持續時間。

* 保留計數決定應保留的特定保留類別的最小備份數。
+
例如、如果備份排程為每日_、而保留計數為_10_、則會保留10個每日備份。

+

NOTE: 利用此功能、最多可保留255份Snapshot複本Data ONTAP 。達到上限後、建立新的Snapshot複本預設會失敗。不過、您可以在Data ONTAP 不一致的情況下設定旋轉原則、以刪除舊的Snapshot複本。

* 保留期間決定保留備份的最短天數。
+
例如、如果備份排程為每日_且保留期間為_10_、則會保留10天的每日備份。



如果您設定SnapMirror複寫、保留原則就會鏡射到目的地磁碟區。


NOTE: 若要長期保留備份複本、您應該使用SnapVault 支援功能。



== 是否要使用來源磁碟區或目的地磁碟區來驗證備份複本？

如果使用SnapMirror或SnapVault SnapMirror、您可以使用SnapMirror或SnapVault 目的地Volume上的Snapshot複本來驗證備份複本、而非使用主儲存系統上的Snapshot複本。使用目的地磁碟區進行驗證、可降低主儲存系統的負載。

*相關資訊*

http://www.netapp.com/us/media/tr-3761.pdf["NetApp技術報告3761：SnapManager 《Oracle的支援：最佳實務做法》"^]
